### ISSUE TITLE
Whats the difference between this and mongoinspector

### ISSUE THREAD

**Issue by isAlmogK** [msavin/Mongol#10]
Also do you need to install both packages.

**Comment by ashishgupta2** [comment]
As per mongoinspector github page it is deprecated and they are suggested to use Mongol. No need to install both, just Mongol should be enough!

https://github.com/msavin/MongoInspector

"Meteor package for visualizing your collections in the browser. **DEPRECATED: Please use Mongol"

**Comment by isAlmogK** [comment]
Thanks didn't see the DEPRECATED message
