### ISSUE TITLE
Mongol shadows Meteor.collection global definition

### ISSUE THREAD

**Issue by majorgilles** [msavin/Mongol#100]
https://github.com/vsivsi/meteor-file-sample-app/issues/2#issuecomment-120780592

https://atmospherejs.com/vsivsi/defender

This was preventing me from installing other packages.

**Comment by rclai** [comment]
There's not much you can about it unless 
1. The giant popular packages decide to stop wrapping `Mongo.Collection` (like `matb33:collection-hooks`, `dburles:mongo-collection-instances` (tons of packages depend on this))
2. MDG addresses it with an in-core solution

Defender will 100% catch something if you use some of popular packages out there like the ones I mentioned above.

**Comment by msavin** [comment]
Indeed - not much we can do, except continue to remind MDG about it :D 

https://github.com/meteor/meteor/issues/3827
