### ISSUE TITLE
Mongol is not working with Angular

### ISSUE THREAD

**Issue by OlivierPT** [msavin/Mongol#103]
After adding msavin:mongol package to the official tutorial application "Meteor with Angular", the mongol UI is not showing after Ctrl - M...

**Comment by JackAdams** [comment]
Might be the same sort of thing as #102. See the fix in the comments there. I'd be interested to hear if it works for you.

I just tried a fork of Mongol that has the fix in it with an angular app (the official tutorial app) and it seemed to work fine.

**Comment by OlivierPT** [comment]
Yes, your solution solved the issue for me also. Great! I close the issue.
Hope the solution will be included in a new version of the package.

Thank you.

**Comment by JackAdams** [comment]
Hey @OlivierPT  -- thanks for getting back to us on this one.  Glad to hear the fix worked!
