### ISSUE TITLE
Updating collection in browser causes ISO date format to be removed.

### ISSUE THREAD

**Issue by sikanhe** [msavin/Mongol#107]
I discovered this issue when i was aggregating docs on serverside using $group and $sum

I realized the aggredated result wasnt summing up correctly as it returned seperated docs for different dates. Some doc had the date in string format ie "2015-09-10T00:00:00.000Z", but some had ISO("2015-09-10T00:00:00.000Z"), and it is recognizing those as different timestamps in $grouping. 

Then I realized all the doc that had string format was ones I updated via Mongol in-browser, it changes ISO date format to string format when i hit update. 

Is this intended or not? is it possible to make it preserve the date format upon update?

**Comment by msavin** [comment]
Good catch. I have a solution for it, coming in next update

**Comment by msavin** [comment]
Fixed  with Mongol 1.2.0 :)
