### ISSUE TITLE
Error running mongol in latest version of meteor

### ISSUE THREAD

**Issue by sagarjs** [msavin/Mongol#115]
I am using meteor 1.2.0.2 on windows.
If i create a new app, and add mongol package, then run the project, i get the following error:

W20150930-17:00:44.438(5.5)? (STDERR) TypeError: Property 'undefined' of object
[object Object] is not a function
W20150930-17:00:44.438(5.5)? (STDERR)     at Package (packages/meteortoys_toykit
/packages/meteortoys_toykit.js:290:1)
W20150930-17:00:44.438(5.5)? (STDERR)     at Package (packages/meteortoys_toykit
/packages/meteortoys_toykit.js:293:1)
W20150930-17:00:44.439(5.5)? (STDERR)     at E:\Sagar\Meteor\myapp.meteor\local
\build\programs\server\packages\meteortoys_toykit.js:325:4
W20150930-17:00:44.439(5.5)? (STDERR)     at E:\Sagar\Meteor\myapp.meteor\local
\build\programs\server\packages\meteortoys_toykit.js:334:3
W20150930-17:00:44.439(5.5)? (STDERR)     at E:\Sagar\Meteor\myapp.meteor\local
\build\programs\server\boot.js:242:10
W20150930-17:00:44.439(5.5)? (STDERR)     at Array.forEach (native)
W20150930-17:00:44.439(5.5)? (STDERR)     at Function._.each._.forEach (C:\Users
\Sagar Sodah\AppData\Local.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_
32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150930-17:00:44.439(5.5)? (STDERR)     at E:\Sagar\Meteor\myapp.meteor\local
\build\programs\server\boot.js:137:5
=> Exited with code: 8

**Comment by msavin** [comment]
Thanks for letting me know, and sorry about the issue! Looking into it issue now.

**Comment by otroboe** [comment]
Same issue for me, in Meteor 1.2.0.2 (Ubuntu 14.04)

**Comment by msavin** [comment]
Should be corrected - please lmk if it helped

**Comment by jonmc12** [comment]
@msavin that fixed it for me, thx!

**Comment by otroboe** [comment]
@msavin Works for me too, thank you !

**Comment by msavin** [comment]
Awesome - thanks for the word!

**Comment by sagarjs** [comment]
Hi,

It's not crashing anymore, but i can't seem to open the Mongol UI using CTRL + M.

**Comment by physicsteacher** [comment]
Started getting this error today. It was working yesterday.

**Comment by msavin** [comment]
Can you remove and re-add please?

**Comment by physicsteacher** [comment]
Works fine when I remove it but crashes when it is added

**Comment by otroboe** [comment]
I have the problem again :(
It's very weird, I dont know why.

I tried to do this:

```
meteor remove msavin:jetsetter msavin:mongol
meteor reset
meteor add msavin:jetsetter msavin:mongol
```

**Comment by derwaldgeist** [comment]
Same problem here, after update to 1.2.0.2

**Comment by nicholaai** [comment]
I'm having the same issue. Run meteor remove msavin:mongol and server runs. meteor add msavin:mongol and it breaks again.

**Comment by derwaldgeist** [comment]
Downgraded to 1.1.0.3, but the problem remained. Doesn't seem to be related to the Meteor update.

**Comment by armandomendivil** [comment]
Update meteortoys:allthings to 2.0.0 version, works for me

**Comment by otroboe** [comment]
@armandomendivil But v2 is not free ?

**Comment by armandomendivil** [comment]
@otroboe  ![meteortoys](https://cloud.githubusercontent.com/assets/5134490/10255243/f894bc5e-68fd-11e5-92d4-1dce19b0c9dc.png)  
meteor update
meteor remove meteortoys:allthings
meteor add meteortoys:allthings
works for me and my team

**Comment by msavin** [comment]
Hmm I wonder why it's not installing V2. It should still install as the base package is free. Can you send a list of your packages?

Then, you may want to remove all of em and run meteor add meteortoys:allthings@2.0.0
