### ISSUE TITLE
Client side errors meteor 1.2

### ISSUE THREAD

**Issue by akshaykmr** [msavin/Mongol#118]
upgrading to meteor 1.2 the app build failed but this was fixed by removing/adding the package. 
Now the build is successful but the package doesn't work in browser.

errors logged in browser console:

> meteortoys_toykit.js:488 Uncaught TypeError: Meteor[p] is not a function
> meteortoys_toykit.js:488 Uncaught TypeError: v8a[L] is not a function

**Comment by lukejagodzinski** [comment]
I get the same error:

Uncaught TypeError: v8a[L] is not a function(anonymous function) **meteortoys_toykit.js:488**
runStartupCallbacks **startup_client.js:30**
ready **startup_client.js:32**

**Comment by TylerShin** [comment]
I got the same problem too.
I know it's annoying to you with Meteor update but I happily waiting that It will be fixed soon.

**Comment by stefanve** [comment]
Same here

**Comment by elie222** [comment]
+1

**Comment by crapthings** [comment]
+1

**Comment by mochtu** [comment]
+1

**Comment by msavin** [comment]
New update pushed with another patch.. looks to be working. Please try again. Hopefully this doesn't break by tomorrow.

**Comment by stefanve** [comment]
Works for me!

**Comment by crapthings** [comment]
It works for me!

**Comment by billh93** [comment]
The update still hasn't reached my location yet :(. 
I'm running 'meteor update mavin:mongol' but it says 'The specified packages are at their latest compatible versions.' I will have to wait a few hours or so.

**Comment by lukejagodzinski** [comment]
Yep, it's working. Thanks!

**Comment by stefanve** [comment]
billh93, try remove/add

**Comment by billh93** [comment]
Ahh okay I know what was the problem. I had msavin:jetsetter installed along with msavin:mongol. That's why updating and removing msavin:mongol didn't do anything.

If anyone has msavin:jetsetter installed, uninstall it and update msavin:mongol and it will work.

**Comment by akshaykmr** [comment]
Thanks! its working.

**Comment by nicholaai** [comment]
Fixed. Thanks

**Comment by guidouil** [comment]
Yes un-installed mongol and jetsetter, then re-installed and everything is fine. Thanks, stay awesome :)

**Comment by mochtu** [comment]
Works now! Thanks,

**Comment by JrodManU** [comment]
Phew, good thing this started working because Constellation just broke today for me xD Thanks for the update!

**Comment by msavin** [comment]
Awesome, glad this is over :D 

@everyone, you may want to take a look at http://toys.meteor.com before the weekend :)
