### ISSUE TITLE
Chrome Styles not showing after installing into project

### ISSUE THREAD

**Issue by Schonne** [msavin/Mongol#12]
Immediately after removing mongo inspector and adding mongol, the styles section of Chrome inspector doesn't show specific styles for elements on the page - it only show the box model  (http://i.stack.imgur.com/BPFut.png). Removing mongol restores chrome's ability to show styles on the page. Quick note: I had your session inspector installed the entire time, if that helps

**Comment by msavin** [comment]
Hmm - not sure what you mean man. Can you send a screenshot of the whole window?

**Comment by Schonne** [comment]
[image: Inline image 1]

**Comment by msavin** [comment]
Not sure that works - all I'm seeing is "[image: Inline image 1]"

**Comment by Schonne** [comment]
Try this link: http://schonne.com/mongol.png

**Comment by msavin** [comment]
Hey man, still not sure what you mean. Can I see some of the source code surrounding the conflict?  Maybe that would help

**Comment by msavin** [comment]
Hey Schonne, can you confirm if you are having the issue after updating to the latest version?

**Comment by Schonne** [comment]
Installed latest version by removing MongoInspector and adding Mongol. The problem has resolved itself - I can inspect elements and see their styles now in Chrome. Consider this issue closed. ;)

**Comment by msavin** [comment]
Awesome! Thanks for letting me know.
