### ISSUE TITLE
Is it possible to show local(cilent only) collections as well?

### ISSUE THREAD

**Issue by sikanhe** [msavin/Mongol#123]
I am making a mostly static site and i am pull server data via meteor methods into a client site collection for caching, is it possible for mongol to show these Mongo.Collection(null) collections ?

**Comment by msavin** [comment]
Coming soon :)

**Comment by sikanhe** [comment]
you're the best ;)

**Comment by sikanhe** [comment]
Oh wait you can just define a local collection with a name instead of just null it will show up, idk why i thought one would need to pass null..

**Comment by Laurentiu-Andronache** [comment]
@msavin This is needed, please don't forget...

**Comment by msavin** [comment]
Hey, so, this is a bit harder than I thought. I'm testing out some new ideas, which may happen with a re-write of Meteor Toys. Still thinking about it, trying to see if the market for it is growing or shrinking. In the meanwhile, I will close this issue. Sorry for the bad news! If it helps, Mongol 4 is out now and its working much better with third party packages.
