### ISSUE TITLE
Mongol_verifyDoc

### ISSUE THREAD

**Issue by stivaugoin** [msavin/Mongol#125]
When I install msavin:mongol, I have this error:

```
W20151221-11:18:00.113(-5)? (STDERR) Error: A method named 'Mongol_verifyDoc' is already defined

W20151221-11:18:00.113(-5)? (STDERR)     at livedata_server.js:1542:15
W20151221-11:18:00.113(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)

W20151221-11:18:00.113(-5)? (STDERR)     at [object Object]._.extend.methods (livedata_server.js:1538:7)

W20151221-11:18:00.113(-5)? (STDERR)     at Object.Meteor.methods (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:157:1)

W20151221-11:18:00.113(-5)? (STDERR)     at Mongol.diffDocumentData.finalData (packages/msavin_mongol/server/methods.js:1:1)

W20151221-11:18:00.113(-5)? (STDERR)     at /home/sbourgoin/projets/anyware-webapp/app/.meteor/local/build/programs/server/packages/msavin_mongol.js:202:4
W20151221-11:18:00.114(-5)? (STDERR)     at /home/sbourgoin/projets/anyware-webapp/app/.meteor/local/build/programs/server/packages/msavin_mongol.js:333:3

W20151221-11:18:00.114(-5)? (STDERR)     at /home/sbourgoin/projets/anyware-webapp/app/.meteor/local/build/programs/server/boot.js:242:10

W20151221-11:18:00.114(-5)? (STDERR)     at Array.forEach (native)

W20151221-11:18:00.114(-5)? (STDERR)     at Function._.each._.forEach (/home/sbourgoin/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
```

Thanks!

**Comment by marxo** [comment]
This might be related to the fact that both jetsetter and mongol are installed. If that is the case, uninstalling either one will solve the issue.

**Comment by Meloncon** [comment]
I experienced this same error when I added Mongol with JetSetter previously installed. I resolved the issue by having both installed, then removing the JetSetter package (which stops the Error Code 8 from happening and leaves just Mongol installed), I then installed JetSetter once more and things seem to be happy and working.

Not sure why there seems to be the requirements to have Mongol installed before JetSetter gets installed, but that seems to be the case. There may be even a reason for it. :)

**Comment by stivaugoin** [comment]
It's not work here. I try JetSetter first and Mongol first, but when I have twice, it's not working. Separately, it's work. But, I have this only in 1 project (I work in 4-5 meteor project, including 2 on 1.2.1). 
It's really strange behavior.

**Comment by boustanihani** [comment]
Same issue here...

**Comment by laurentpayot** [comment]
Same here…

**Comment by stivaugoin** [comment]
**Work around**
Uninstall msavin:mongol and msavin:jetsetter
Install meteortoys:allthings
Mongol and JetSetter is available free
