### ISSUE TITLE
Spaces appearing in mongol property names, editing issues

### ISSUE THREAD

**Issue by ArcaneEngineer** [msavin/Mongol#126]
Disclaimer: [The live demo](http://mongol.meteor.com/) appears to work fine for me.

I'm getting a ton of spaces both before and after each property name - so much so that I can't see the name without scrolling way over to the right, which is extremely tedious while trying to work.

I also can't seem to edit things properly, for example, I create a new entry in a collection, but when I hit update document, I cannot click or use the keyboard to move my cursor between the braces so I can add new properties. Which obviously completely stymies me.

Lastly I see that my Mongol doesn't look like the demo version, which shows the version at the top. Mine shows nonesuch. Also the fonts and syntax highlighting look different so maybe I have an older version. I see no difference between `meteor add msavin:mongol` and the MeteorToys 2.0.0 version.

There are no errors visible in Windows console interface from which I run meteor.

It's all rather strange and I think it has to do with discrepancies in my setup. If you could tell me what info to provide to help solve this, I'd be happy to supply!

This happens on FF 43 and Chrome 47. Meteor version 1.2.1.

**Comment by ArcaneEngineer** [comment]
Alternatively, I'd be happy to just get an install package that works with mongol.

**Comment by msavin** [comment]
Thanks for the alert, I will look into it soon. Can you please try a clean app and see if the issue persists? If so, a list of your packages would be helpful to start.

**Comment by ArcaneEngineer** [comment]
Thanks msavin, a fresh app fixed it. Doh.

[proj.zip](https://github.com/msavin/Mongol/files/87280/eflstats.zip)

It's odd, since the original project - attached - was very simple. I probably did something stupid - new to meteor. Anyway, we can close unless you want to look into what was causing that...

**Comment by ArcaneEngineer** [comment]
The "many spaces" was a CSS issue - of my own making (see final entry in CSS).

**Comment by ArcaneEngineer** [comment]
Alright, having removed the annoying "spaces" part of this issue, I'm re-opening as I can now see no reason why the editing should not be working - Basically everything is fresh, including HTML & JS with no CSS. Packages:
[packages.txt](https://github.com/msavin/Mongol/files/87445/packages.txt)

I try to edit and simply can't get between the braces! It's insane!

**Comment by ArcaneEngineer** [comment]
OK... Editing _is_ a Firefox issue, or at least my local FF config does not allow me to edit. In Chrome, with the "spaces" issue resolved, I can now edit just fine. That's good enough for me.

I'll leave this open as you may want to look at what's causing the problem in FF - attached simple test.
[test.zip](https://github.com/msavin/Mongol/files/87496/test.zip)

**Comment by msavin** [comment]
Hey - thanks for the tip - I've tried to replicate but could not. I recall Firefox has a quirk with contenteditable, but trying now on a new version does not seem to have any issues. If it continues, please let mek now.
