### ISSUE TITLE
0.7.2 package source

### ISSUE THREAD

**Issue by keesee** [msavin/Mongol#127]
Hi there.  I looked through branched and releases, but can't find the 0.7.2 branch.  Its the version I'm running and I would like to make some template tweaks.  so it works with Bootstrap and/or semantic. 
New to meteor and while I have the older version in cache, I don't know where the source files are, just meteor tools and packing system files.  just the cached files. 

Thanks 
JK

**Comment by msavin** [comment]
Hey man, unfortunately I do not have any way to trace back the source code. My best advice would be to go for the latest as a lot of changes hit in 1.0 and then the versions after that. Mongol should not have any issues working with Bootstrap/etc - if you see some please let me know.
