### ISSUE TITLE
Mongol + Lodash + Underscore

### ISSUE THREAD

**Issue by sylido** [msavin/Mongol#128]
Seems like lodash and underscore are mixing up and mongol expects a contains method defined but it doesn't find it ? I've had both lodash and underscore in the project for a hwile now and I didn't have this problem. Any idea on how to resolve this on my end ?

```
Exception while invoking method 'Mongol_update' TypeError: Object  has no method 'contains'
I20160126-16:58:01.298(-7)?     at packages/msavin_mongol/server/utility_functions.js:43:1
I20160126-16:58:01.298(-7)?     at arrayEach (/root/.meteor/packages/stevezhu_lodash/.4.0.0.1pu5j6r++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:446:11)
I20160126-16:58:01.298(-7)?     at Function.forEach (/root/.meteor/packages/stevezhu_lodash/.4.0.0.1pu5j6r++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:7482:11)
I20160126-16:58:01.298(-7)?     at Object.Mongol.diffDocumentData (packages/msavin_mongol/server/utility_functions.js:41:1)
I20160126-16:58:01.298(-7)?     at [object Object].Meteor.(anonymous function).Mongol_update (packages/msavin_mongol/server/methods.js:1:1)
I20160126-16:58:01.298(-7)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160126-16:58:01.298(-7)?     at livedata_server.js:708:19
I20160126-16:58:01.298(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160126-16:58:01.299(-7)?     at livedata_server.js:706:40
I20160126-16:58:01.299(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

**Comment by msavin** [comment]
Hmm, I'm not sure what we can do here since they both use the same variable name. I could suggest you edit one of the variable names? Maybe loading lodash after Mongol would help. Otherwise - I'm not sure if there is much that could be done on the side of Mongol

**Comment by sylido** [comment]
Well maybe substituting underscore with lodash would help ? 
I solved it by doing `_.contains = _.includes;` in one of my files.
I'll close this issue, thanks.

**Comment by msavin** [comment]
Cool - I believe Meteor still uses underscore on the server so Meteor Toys will follow that default. If they update it, I'll change the plan.  Glad you got it working :+1:
