### ISSUE TITLE
Two very different license on the project

### ISSUE THREAD

**Issue by serut** [msavin/Mongol#129]
Hi,

On one hand, you wrote on the README (https://github.com/msavin/Mongol/blob/master/README.md#about) that Mongol is limited to a single user. But on another hand, you put the MIT license in your documentation directory : https://github.com/msavin/Mongol/blob/master/documentation/LICENSE.md

Can you clean up that ?

**Comment by msavin** [comment]
Thanks for the heads up. The LICENSE.md just neede to be removed as I've begun to cover everything under Meteor Toys license.
