### ISSUE TITLE
error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by neo-6** [msavin/Mongol#130]
Hi：
when i use "meteor add mavin:mongol"
Errors while adding package:
While downloading dburles:mongo-collection-instances@0.3.4...:
error: connect ETIMEDOUT

While downloading lai:collection-extensions@0.1.4...:
error: connect ETIMEDOUT

While downloading meteortoys:toykit@2.2.1...:
error: connect ETIMEDOUT

While downloading msavin:mongol@1.6.2...:
error: connect ETIMEDOUT

how can I use Mongol-master config to my meteor project manually?

**Comment by msavin** [comment]
Hmm - this sounds like an issue with Meteor's ability to download packages (I believe there was some scheduled downtime for it a while ago). It should work if you try again. If the issue persists please let me know.
