### ISSUE TITLE
Object.observe deprecation

### ISSUE THREAD

**Issue by dubielzyk** [msavin/Mongol#131]
On latest version of Chrome I keep getting:
`'Object.observe' is deprecated and will be removed in M50, around April 2016. See http://chromestatus.com/features/6147094632988672 for more details`

**Comment by Incisive** [comment]
Also seeing this after upgrading chrome.

**Comment by msavin** [comment]
Fix is on the way. It's a shame they deprecated such a cool feature.

**Comment by andersr** [comment]
Chrome 50 has now been released and Object.observe has been [removed](https://www.chromestatus.com/features/6147094632988672). Any updates on this fix?

**Comment by msavin** [comment]
Sorry that its taking so long - hands are full. However, Meteor Toys try to use Object.observe first, and if its not available, they fall back to polling every second or so. It should work for as long as Chrome returns undefined for Object.observe. If Chrome is not already making Object.observe undefined, I can suggest hacking it at least for now.

``` javascript
if (Package["msavin:mongol"]) {
    Object.observe = undefined;
}
```

**Comment by maxmatthews** [comment]
This was throwing a warning in the Chrome JS console for a while about being depreciated but now that they've completely removed it, Chrome automatically sets `Object.observe = undefined`, so it no longer throws a warning, making your code block above unnecessary.
Thanks for all your hard work @msavin, looking forward to the updates whenever they come out.

**Comment by msavin** [comment]
Mongol 2.0 has solved this issue. To get the latest Mongol, run `meteor update` or re-install the package.
