### ISSUE TITLE
Mongol with role based permission

### ISSUE THREAD

**Issue by faavictoriano** [msavin/Mongol#134]
Good day!

Can we use mongol with role based permission? The Admin roles only can use ctrl+m ? the the subscribe with role based?

**Comment by faavictoriano** [comment]
i am working with role based permission and i use 

var loggedInUser = this.userId;
   if (Roles.userIsInRole(loggedInUser,['admin'])) {
        return MyCollection.find();
    }

but there's any way to disable the ctrl+m if the user not loggined?

**Comment by msavin** [comment]
Hey - this is not included/recommended as Mongol is intended for development purposes only.
