### ISSUE TITLE
Getting 'Object.observe' is deprecated in Google Chrome

### ISSUE THREAD

**Issue by phocks** [msavin/Mongol#135]
> 'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

And it's April now, so I'm thinking this may break Mongol soon perhaps.

**Comment by msavin** [comment]
Thanks for heads up - it should not break Mongol because the Mongol is unbreakable ^_^ ... and because it falls back to polling if Object.observe returns falsey

**Comment by msavin** [comment]
Mongol 2.0 has solved this issue. To get the latest Mongol, run `meteor update` or re-install the package.
