### ISSUE TITLE
JSON Syntax Doesn't Show Up in 2.0.1

### ISSUE THREAD

**Issue by maxmatthews** [msavin/Mongol#136]
Attached screenshots of what is happening and what it should look like. Looks like toykit.css line 548 is the issue. Just need to remove it and they show up again. Will create a pull request if I get a chance.
![screen shot 2016-05-10 at 10 46 11 am](https://cloud.githubusercontent.com/assets/4709710/15150758/801d93de-169c-11e6-877a-a056bb50a55c.png)
![screen shot 2016-05-10 at 10 46 02 am](https://cloud.githubusercontent.com/assets/4709710/15150759/801fde00-169c-11e6-85fe-203944d8124b.png)

**Comment by msavin** [comment]
Thanks for the report. Are those screenshots of Mongol? Also, can you
please send a package list?

**Comment by maxmatthews** [comment]
Yes, those are screenshots from mongol. Just didn't want to reveal my whole DB structure. :-p
Here's my package list

```
accounts-password          1.1.8  Password support for accounts
accounts-ui                1.1.9  Simple templates to add login widgets to an app
alanning:roles             1.2.15  Authorization package for Meteor
blaze-html-templates       1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
coffeescript               1.0.17  Javascript dialect with fewer braces and semicolons
ecmascript                 0.4.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim                   4.5.10  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome    4.5.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
fourseven:scss             3.4.3  Style with attitude. Sass and SCSS support for Meteor.js (with autoprefixer and sourcemaps).
jagi:astronomy             1.2.10* Model layer for Meteor
jagi:astronomy-relations   1.0.0  Relations for Meteor Astronomy
jagi:astronomy-validators  1.1.2  Validators for Meteor Astronomy
jhartma:cjsx               2.4.1  Write React Components for Meteor in Coffeescript
jquery                     1.11.8  Manipulate the DOM using CSS selectors
kadira:flow-router         2.12.1  Carefully Designed Client Side Router for Meteor
meteor-base                1.0.4  Packages that every Meteor app needs
mobile-experience          1.0.4  Packages for a great mobile user experience
momentjs:moment            2.13.1  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                      1.1.7  Adaptor for using MongoDB and Minimongo over DDP
msavin:mongol              2.0.1  In-App MongoDB Editor.. now works better than ever!
okgrow:analytics           1.0.5  Complete Google Analytics, Mixpanel, KISSmetrics (and more) integration for Meteor
react-meteor-data          0.2.9  React mixin for reactively tracking Meteor data
session                    1.1.5  Session variable
standard-minifier-css      1.0.6  Standard css minifier used with Meteor apps by default.
standard-minifier-js       1.0.6  Standard javascript minifiers used with Meteor apps by default.
tracker                    1.0.13  Dependency tracker to allow reactive callbacks
twbs:bootstrap             3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
```

Looks like the problem is coming from MeteorToys, although that may be intentional.

**Comment by maxmatthews** [comment]
Never mind on me fixing it myself. Looks like the CSS file is in MeteorToys which isn't open sourced so I can't do a pull request. I'll just wait patiently.

**Comment by lonyele** [comment]
same here too. before, when I click collections on mongol, its background is dark grey and I can update the text normally. now it is white background and when I try to update it, texts are becoming white which I can't write anything...

**Comment by gulci** [comment]
Having the same issue as lonyele. Instead of the light-gray maxmatthews is getting, I just get white.

![screen shot 2016-05-10 at 1 03 48 pm](https://cloud.githubusercontent.com/assets/8071536/15160682/b966b626-16af-11e6-8e88-10ff1c069af9.png)
