### ISSUE TITLE
Some chrome extension shortcut conflicts with Mongol Ctrl-M

### ISSUE THREAD

**Issue by vjrj** [msavin/Mongol#137]
Similar to #20 I cannot open the Mongol console because of a conflicting chrome extension.

The old `Session.set("Mongol_settings_display", true)` workaround does not work with the current Mongol version. Any current way to open Mongol via the console or to redefine the shortcut?

TIA

**Comment by msavin** [comment]
MeteorToys.open() and close() should help. There's also an (not yet
announced) meteortoys:toggle package.

**Comment by vjrj** [comment]
Great... thanks!
