### ISSUE TITLE
where do I put this line to add new collection?

### ISSUE THREAD

**Issue by ghost** [msavin/Mongol#138]
I'm trying to add a collection using `Package["msavin:mongol"].Mongol.showCollection('collection_name');`  on server.js on meteor 1.3 but, it give me `Cannot call method 'showCollection' of undefined` error. where should I put this? I can create PR to update the doc once I figure it out. Thanks.

I tried this: `import Mongol from 'meteor/msavin:mongol';`
but still get error: `TypeError: Object [object Object] has no method 'showCollection'`

**Comment by pcoutin** [comment]
same

`import {Mongol} from 'meteor/msavin:mongol'` doesn't work either...

if I do import Mongol from 'meteor/msavin:mongol'; I just get null for Mongol

**Comment by pcoutin** [comment]
Package['msavin:mongol'] on `meteor shell` equals {}.

**Comment by msavin** [comment]
Hey - sorry that it took so long to get to this. The issue is that you need to run that on the client. I'll double check the readme to make sure its more clear.

**Comment by msavin** [comment]
On another note, Mongol 4 is out - you might want to try it. It's working much better with third party packages now.
