### ISSUE TITLE
Ctrl + M not working in Mac Chrome browser

### ISSUE THREAD

**Issue by lesliechw** [msavin/Mongol#139]
Any advice? Never able to load up Mongol. Please advice, thank you.

**Comment by webmagnets** [comment]
I am having the same issue.

**Comment by webmagnets** [comment]
I was having this problem, but now it resolved itself. Are you still experiencing the issue?

**Comment by msavin** [comment]
@lesliechw bump.

There was like a buggy Chrome release, maybe that was it?

**Comment by msavin** [comment]
Closing this issue as I have heard about it and am not able to reproduce. If you issue is still recurring, please let me now.
