### ISSUE TITLE
Login dialog never closes if you login through Mongol mini-window.

### ISSUE THREAD

**Issue by ssteinerx** [msavin/Mongol#14]
Start app not logged in.

Try to sign in from within Mongol mini-window.

Dialogs appear both in Mongol mini-window, and main window.

Log in using Mongol mini-window.

Sign-in happens, but login dialog in Mongol mini-window doesn't and cannot be closed.

**Comment by ssteinerx** [comment]
The Mongol mini-window version of the login dialog also interferes with the main one leading to "Username must be at least 3 characters long" error message when when trying to login from main window.  IOW with Mongol installed, you MUST login from Mongol's mini-window version of the dialog which then won't close.

**Comment by ssteinerx** [comment]
And, if you hit refresh after logging in, you stay logged in, but Mongol reports that you are not:

https://www.dropbox.com/s/kjkhsfwmp7bue3v/Screenshot%202015-02-22%2008.12.55.png?dl=0

**Comment by msavin** [comment]
Tried to replicate but did not have the same result. I did push an update surrounding account management thought - can you check if that made any difference?

**Comment by JackAdams** [comment]
I was able to reproduce this bug. #17 has a fix for this, but it needs a bit more polishing. At least the account panel doesn't interfere with the sign-in process anymore.

**Comment by msavin** [comment]
@ssteinerx can you confirm if you are experiencing the issue with the update?

**Comment by ssteinerx** [comment]
Will do, going back to that project momentarily.

**Comment by msavin** [comment]
Assuming this worked fine. Let us know if you still have issues with it.
