### ISSUE TITLE
ctrl + M not working in meteor 1.4.2

### ISSUE THREAD

**Issue by jayspirits** [msavin/Mongol#142]

**Comment by msavin** [comment]
Odd - was this working before you updated?

Also: can you try the `meteortoys:toggle` package?

**Comment by iamfeek** [comment]
Hey msavin!

I have been using this package for the longest time and it just suddenly decides to stop working on me.

My Stack:
Ubuntu 16.10
Meteor 1.4.2.3
Google Chrome

I have tried researching from previous issues and these are the things that I have tried.
1. `Session.set("Mongol_settings_display", true);`
2. `disabling all Chrome extensions`
3. `meteor add meteortoys:toggle`
4. `inspect element to watch for rendering of mongol UI.`

Useful Information
*** NOTE: Chrome Extensions have ALL been disabled.**

**Meteor Version: 1.4.2.3**
**meteortoys:toggle@3.0.0**
**meteortoys:toykit@3.0.4**
**msavin:mongol@2.0.1**
**session@1.1.7**

EDIT: After typing this. I testing on my mac with Chrome and it is working fine.

**Comment by cosmin-novac** [comment]
I had the same problem yesterday after updating meteor. I simply went ahead and removed mongol, then added it back again. It's working now.

**Comment by iamfeek** [comment]
@tenshis I did the same but, unfortunately, to no avail.

**Comment by cosmin-novac** [comment]
Perhaps try to move it to the top of your packages list? The readme says it helps sometimes.

**Comment by msavin** [comment]
Can you try to open it with meteortoys:toggle

**Comment by iamfeek** [comment]
@msavin adding the package does not show any visuals. 

meteortoys:toggle@3.0.0
msavin:mongol@2.0.1

MeteorToys.open() returns
` MeteorToys is not defined`

**Comment by iamfeek** [comment]
@tenshis I have tried that, still the same dude. Urghhhh!

**Comment by msavin** [comment]
Strange - can you send the output of your package list, preferably
`formatted`

**Comment by iamfeek** [comment]
@msavin 
meteortoys:toggle
msavin:mongol
meteor-base@1.0.4
mobile-experience@1.0.4
mongo@1.1.14
blaze-html-templates@1.0.4
reactive-var@1.0.11
jquery@1.11.10
tracker@1.1.1

standard-minifier-css@1.3.2
standard-minifier-js@1.2.1
es5-shim@4.6.15
ecmascript@0.6.1
shell-server@0.2.1
browser-policy@1.0.9
react-meteor-data
accounts-ui@1.1.9
accounts-password@1.3.3
accounts-base@1.2.14
themeteorchef:bert
check@1.2.4

fortawesome:fontawesome
kadira:dochead
teamon:tinymce
smalljoys:uploadcare
alanning:roles
mdg:geolocation
kadira:flow-router-ssr
c12o16h1:meteor-seo
mfpierre:chartist-js
dburles:google-maps
materialize:materialize

session
meteortoys:allthings

**Comment by msavin** [comment]
So - the first issue could be with allthings and Mongol. All Things
includes Mongol. Please remove all Toy packages and then add
meteortoys:allthings, and then maybe try to move it to top of list

**Comment by msavin** [comment]
Hey, is it safe to assume these issues have been revolved?  If so, I will proceed to close to the issue.

**Comment by msavin** [comment]
I just updated Mongol to 4.0. If you still have some outstanding issues, you may want to try it.

Key thing may be to move it to the top of your package list. Additionally, in case there is a non-standard keyboard set up, you can try meteortoys:toggle.
