### ISSUE TITLE
mogol is deployed to production version

### ISSUE THREAD

**Issue by NanIsNotANum** [msavin/Mongol#146]
Hi,

Thanks for the awesome tool for meteor development.

I recently discovered that mongol still works on my production version...
if I type "ctrl+m", the mongol window shows up on my "production" website...
but I haven't changed any deploy setting(I have been using mupx)

Do you maybe have any idea what is going on?

Thanks a lot!

**Comment by msavin** [comment]
Hey, this sounds very strange. Can you please send your Meteor version and
package list

**Comment by NanIsNotANum** [comment]
Thanks a lot :)

**Meteor version :METEOR@1.3.1**

**package list (recently commented out mongol for data security concern)**

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

fourseven:scss
cwaring:modernizr
reactive-dict
kadira:flow-router
kadira:blaze-layout
arillo:flow-router-helpers
accounts-password
accounts-base
accounts-facebook
service-configuration
aldeed:collection2
aldeed:simple-schema
themeteorchef:bert
email
edgee:slingshot
classcraft:knox
okland:accounts-phone
matb33:collection-hooks
\# msavin:mongol
dandv:jquery-rateit
fortawesome:fontawesome
check
random
http
momentjs:moment
drewy:datetimepicker
gwendall:reactive-var-methods
raix:handlebar-helpers
kevohagan:sweetalert
canotto90:swal-forms
themeteorchef:jquery-validation
session

jonblum:jquery-cropper
jparker:crypto-sha256
meteorhacks:picker
froala:editor
simple:reactive-method
poetic:materialize-scss
webtempest:animate
force-ssl
okgrow:analytics
kadira:debug
percolate:synced-cron
biasport:facebook-sdk

**package version list (if needed)**

accounts-base@1.2.5
accounts-facebook@1.0.8
accounts-oauth@1.1.11
accounts-password@1.1.7
aldeed:collection2@2.9.1
aldeed:collection2-core@1.1.1
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.3
arillo:flow-router-helpers@0.5.1
autoupdate@1.2.7
babel-compiler@6.6.1
babel-runtime@0.1.7
base64@1.0.7
biasport:facebook-sdk@0.2.3_1
binary-heap@1.0.7
blaze@2.1.6
blaze-html-templates@1.0.3
blaze-tools@1.0.7
boilerplate-generator@1.0.7
caching-compiler@1.0.3
caching-html-compiler@1.0.5
callback-hook@1.0.7
canotto90:swal-forms@0.3.0
check@1.1.3
classcraft:knox@0.9.11
coffeescript@1.0.16
cwaring:modernizr@3.0.0_1
dandv:jquery-rateit@1.0.22_2
ddp@1.2.4
ddp-client@1.2.4
ddp-common@1.2.4
ddp-rate-limiter@1.0.3
ddp-server@1.2.5
deps@1.0.11
diff-sequence@1.0.4
drewy:datetimepicker@1.0.3
ecmascript@0.4.2
ecmascript-runtime@0.2.9
edgee:slingshot@0.7.1
ejson@1.0.10
email@1.0.11
es5-shim@4.5.9
facebook@1.2.5
fastclick@1.0.10
force-ssl@1.0.10
fortawesome:fontawesome@4.4.0_1
fourseven:scss@3.4.1
froala:editor@2.3.4
geojson-utils@1.0.7
gwendall:reactive-var-methods@0.1.0
hot-code-push@1.0.3
html-tools@1.0.8
htmljs@1.0.8
http@1.1.4
id-map@1.0.6
jonblum:jquery-cropper@2.3.0
jparker:crypto-core@0.1.0
jparker:crypto-sha256@0.1.1
jquery@1.11.7
kadira:blaze-layout@2.3.0
kadira:debug@3.2.2
kadira:flow-router@2.11.0
kadira:runtime-dev@0.0.1
kevohagan:sweetalert@1.0.0
launch-screen@1.0.10
livedata@1.0.17
localstorage@1.0.8
logging@1.0.11
matb33:collection-hooks@0.8.1
mdg:validation-error@0.5.1
meteor@1.1.13
meteor-base@1.0.3
meteorhacks:kadira@2.23.4
meteorhacks:meteorx@1.3.1
meteorhacks:picker@1.0.3
minifier-css@1.1.10
minifier-js@1.1.10
minimongo@1.0.13
mobile-experience@1.0.3
mobile-status-bar@1.0.11
modules@0.5.2
modules-runtime@0.6.2
momentjs:moment@2.14.4
mongo@1.1.6
mongo-id@1.0.3
mongo-livedata@1.0.11
npm-bcrypt@0.7.8_2
npm-mongo@1.4.42
oauth@1.1.9
oauth2@1.1.8
observe-sequence@1.0.10
okgrow:analytics@2.0.0
okland:accounts-phone@0.0.21
ordered-dict@1.0.6
percolate:synced-cron@1.3.2
poetic:materialize-scss@1.97.5_2
promise@0.6.6
raix:eventemitter@0.1.3
raix:handlebar-helpers@0.2.5
random@1.0.8
rate-limit@1.0.3
reactive-dict@1.1.6
reactive-var@1.0.8
reload@1.1.7
retry@1.0.6
routepolicy@1.0.9
service-configuration@1.0.8
session@1.1.4
sha@1.0.6
simple:reactive-method@1.0.2
spacebars@1.0.10
spacebars-compiler@1.0.10
srp@1.0.7
standard-minifier-css@1.0.5
standard-minifier-js@1.0.5
templating@1.1.8
templating-tools@1.0.3
themeteorchef:bert@2.1.0
themeteorchef:jquery-validation@1.14.0
tracker@1.0.12
ui@1.0.10
underscore@1.0.7
url@1.0.8
webapp@1.2.7
webapp-hashing@1.0.8
webtempest:animate@0.1.9
zimme:active-route@2.3.2

**Comment by msavin** [comment]
I just did a test, and when pushing Meteor into production, it removes Mongol. 

Can you try to run `meteor --production` to see what happens?

Also, you might want to make sure that MUP is not deploying your app in development mode.

**Comment by NanIsNotANum** [comment]
Thanks for the quick reply, I will try it and reply ASAP

**Comment by NanIsNotANum** [comment]
Hey, 
it turns out that I was deploying with another machine, and the mup file was set up with 
debug mode, and after I turn off the debug mode, everything went well again.

Thanks a lot for the good effort!
