### ISSUE TITLE
There was an error updating your document. Please review your changes and try again.

### ISSUE THREAD

**Issue by dredl** [msavin/Mongol#147]
Hi everyone!
After updating from aldeed:collection2 to aldeed:collection2-core and to npm simpl-schema package i cant change any data in mongol. In console i got following error:
```
Exception while invoking method 'Mongol_update' Error: Expected 'services' to be a modifier operator like '$set'
     at C:\Users\11192\WebstormProjects\WFDraft\node_modules\simpl-schema\dist\doValidation.js:312:15
     at Function._.each._.forEach (C:\Users\11192\WebstormProjects\WFDraft\node_modules\underscore\underscore.js:158:9)
     at checkModifier (C:\Users\11192\WebstormProjects\WFDraft\node_modules\simpl-schema\dist\doValidation.js:309:26)
     at doValidation (C:\Users\11192\WebstormProjects\WFDraft\node_modules\simpl-schema\dist\doValidation.js:351:5)
     at ValidationContext.validate (C:\Users\11192\WebstormProjects\WFDraft\node_modules\simpl-schema\dist\ValidationContext.js:217:57)
     at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:399:33)
     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2-core/collection2.js:187:25)
     at [object Object].Meteor.(anonymous function).Mongol_update (packages\msavin_mongol.js:210:2483)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
     at packages/ddp-server/livedata_server.js:719:19
```

**Comment by sgoudie** [comment]
+1 Same here.

**Comment by adamthewan** [comment]
+2 same! :(

**Comment by sgoudie** [comment]
@msavin is there any plan to fix this? Be good to know as we use Mongol everyday!

**Comment by msavin** [comment]
Oh boy. Will take a look at this during the week :)

**Comment by sgoudie** [comment]
🙌 Thanks Max!

**Comment by adamthewan** [comment]
@msavin Did you manage to solve it?

**Comment by msavin** [comment]
Update is coming. Please see: https://docs.google.com/a/maxsavin.com/forms/d/e/1FAIpQLScNwc2ni3oO5HWtsaoW6q4YDU_z_j6XiqPyUCz9Dt9FQ52qeA/viewform?c=0&w=1

**Comment by msavin** [comment]
hey @everyone can you please try the 4.0 and let me know how its working for you? its working on my end :)

**Comment by sgoudie** [comment]
Awesome, thanks Max. My key doesn't work anymore though. Do you offer a discount for upgrades from 3?

**Comment by sgoudie** [comment]
Hey @msavin, upgraded to 4 here and still not allowing updates:

```
I20170620-09:20:12.334(1)?     at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:399:33)
I20170620-09:20:12.336(1)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2-core/collection2.js:187:25)
I20170620-09:20:12.338(1)?     at [object Object].Meteor.(anonymous function).Mongol_update (packages/msavin_mongol.js:40:2919)
I20170620-09:20:12.338(1)?     at packages/check.js:129:16
I20170620-09:20:12.340(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170620-09:20:12.342(1)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
I20170620-09:20:12.342(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
I20170620-09:20:12.345(1)?     at packages/ddp-server/livedata_server.js:719:19
I20170620-09:20:12.346(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170620-09:20:12.349(1)?     at packages/ddp-server/livedata_server.js:717:40
I20170620-09:20:12.351(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
```

**Comment by msavin** [comment]
Ahh shoot. 

 - does this package drop some kind of global variable that can be used to detect it? 
 - It does seem like you are using an atmosphere package, not NPM, right?
 - Can you provide some kind of reproduction?

**Comment by isZumpo** [comment]
I'm also having this problem when running aldeed:collection2-core with npm simpl-schema. I'm using this schema:

`ContractorSchema = new SimpleSchema({
    name: {
        type: String,
        label: "Name",
        max: 60
    },
    address: {
        type: String,
        label: "Address",
        max: 60
    },
    email: {
        type: String,
        label: "Email",
        max: 60,
        regEx: SimpleSchema.RegEx.Email
    },
    phone: {
        type: String,
        label: "Phone",
        max: 60
    },
    createdAt: {
        type: Date,
        autoValue: () => {
            if(!this.isSet) {
                return new Date();
            }
        },
        uniforms: {
            hidden: true
        }
    },
    editedAt: {
        type: Date,
        autoValue: () => {
            return new Date();
        },
        uniforms: {
            hidden: true
        }
    }
});`

Also getting the error message:

> 
 Exception while invoking method 'Mongol_update' Error: Expected 'name' to be a modifier operator like '$set'
> 

when trying to update the collection item with mogol

**Comment by lc3t35** [comment]
Hi, FYI I have the same error message with restivus 
````
W20171018-09:11:43.533(2)? (STDERR) Error: Expected 'userId' to be a modifier operator like '$set'
W20171018-09:11:43.534(2)? (STDERR)     at /xxxxx/node_modules/simpl-schema/dist/doValidation.js:312:15
W20171018-09:11:43.536(2)? (STDERR)     at Function._.each._.forEach (/xxxxx/node_modules/underscore/underscore.js:158:9)
W20171018-09:11:43.537(2)? (STDERR)     at checkModifier (/xxx/node_modules/simpl-schema/dist/doValidation.js:309:26)
W20171018-09:11:43.538(2)? (STDERR)     at doValidation (/xxx/node_modules/simpl-schema/dist/doValidation.js:349:5)
W20171018-09:11:43.539(2)? (STDERR)     at ValidationContext.validate (/xxx/node_modules/simpl-schema/dist/ValidationContext.js:216:57)
W20171018-09:11:43.539(2)? (STDERR)     at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:399:33)
W20171018-09:11:43.540(2)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2-core/collection2.js:187:25)
W20171018-09:11:43.541(2)? (STDERR)     at Object.put.action (packages/nimble_restivus/lib/restivus.coffee:162:40)
W20171018-09:11:43.542(2)? (STDERR)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
W20171018-09:11:43.543(2)? (STDERR)     at packages/nimble_restivus/lib/route.coffee:59:33
````

**Comment by Floriferous** [comment]
Any update on this? Started seeing this error today.

**Comment by Lucbug** [comment]
Same here

**Comment by msavin** [comment]
Ugh.. sorry folks. I'm considering doing a total re-write of Mongol / Meteor Toys, but the market has become much smaller compared to the hype days. I might have to set the price at $199 for this one. I would love to hear any feedback, thoughts, requests, etc 😄

**Comment by msavin** [comment]
Improved compatibility with Collection2 is here. Please try the latest versions. If you run into issues, please open a new thread.
