### ISSUE TITLE
React version?

### ISSUE THREAD

**Issue by merlinstardust** [msavin/Mongol#149]
I know that this doesn't get bundled for production, so Blaze and related code doesn't weight down the client, however it would be nice to see a React version. I'd like to remove all Blaze related code from my project even in development. So it would be nice to see a React version of this made.

**Comment by msavin** [comment]
I'm looking to do something new here.. hope to have more to share soon.

If Mongol dynamically imported Blaze when you'd open it, would that be okay for you or would you still prefer if it were in React?

**Comment by merlinstardust** [comment]
I don't know how I missed this back then (guess my notifications weren't turned on).

Dynamic import would be better but I would still prefer React.

What did you end up doing?
