### ISSUE TITLE
Ionic app runs in different port from a meteor server. How can we able to show the minimongo data in ionic serve port?

### ISSUE THREAD

**Issue by kevinklinegargar** [msavin/Mongol#151]
My app is using Ionic framework and angular2 for frontend and meteorjs as the backend. They are running in different port. Example the main app is running on port localhost:8100  and the meteor server is on localhost:3000. The mongol can only be open in localhost:3000 but the minimongo is on the localhost:8100. There's a way the mongol can be open in the ionic app (localhost:8100) ?

**Comment by msavin** [comment]
Unfortunately, there is no such way to do this.
