### ISSUE TITLE
Session dependency needs to be made explicit

### ISSUE THREAD

**Issue by neil-s** [msavin/Mongol#153]
1. Create a fresh meteor app with no packages installed
2. Install mongol
3. Run meteor

Console error: "Uncaught ReferenceError: Session is not defined mongol"

Looks like session is no longer installed with meteor by default, so this dependency should be made explicit.

**Comment by msavin** [comment]
Any chance you are using an old version of MongoInspector? Mongol no longer uses Session

**Comment by neil-s** [comment]
Yup, I was. Getting meteor to agree to installing a new package removed that dependency.

Sorry for the noise and thanks for being so responsive to noob questions!
