### ISSUE TITLE
Meteor 1.6.1 and meteortoys:allthings 4.0.0 shows only the users collection

### ISSUE THREAD

**Issue by hanskohls** [msavin/Mongol#155]
I updated a project to Meteor 1.6.1 this morning and ever since doing so the only collection I can see in Mongol Pro is 'users'. 

I'm not sure what is causing it, but it hapened immediately after this update. I can see no error messages either on the server or the client. 

List of my packages is here: 

accounts-base@1.4.2
accounts-password@1.5.0
aldeed:autoform@6.2.0
aldeed:collection2@2.7.1
aldeed:simple-schema@1.5.3
allow-deny@1.1.0
autoupdate@1.4.0
babel-compiler@7.0.0
babel-runtime@1.2.2
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.4.0
caching-compiler@1.1.11
caching-html-compiler@1.1.2
callback-hook@1.1.0
check@1.3.0
coffeescript@1.0.17
ddp@1.4.0
ddp-client@2.3.1
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.3.0
ecmascript@0.10.0
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.0
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
es5-shim@4.7.3
fourseven:scss@4.5.4
geojson-utils@1.0.10
gfk:notifications@1.1.4
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
id-map@1.1.0
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.1.1
less@2.7.12
livedata@1.0.18
localstorage@1.2.0
logging@1.1.19
mdg:validated-method@1.1.0
mdg:validation-error@0.2.0
meteor@1.8.2
meteor-base@1.3.0
meteortoys:allthings@4.0.0
meteortoys:authenticate@4.0.0
meteortoys:autopub@4.0.0
meteortoys:blueprint@4.0.0
meteortoys:email@4.0.0
meteortoys:hotreload@4.0.0
meteortoys:listen@4.0.0
meteortoys:method@4.0.0
meteortoys:mobile@4.0.0
meteortoys:pub@4.0.0
meteortoys:result@4.0.0
meteortoys:shell@4.0.0
meteortoys:status@4.0.0
meteortoys:sub@4.0.0
meteortoys:throttle@4.0.0
meteortoys:toggle@4.0.0
meteortoys:toykit@4.0.1
minifier-css@1.3.0
minifier-js@2.3.1
minimongo@1.4.3
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.11.3
modules-runtime@0.9.2
momentjs:moment@2.10.6
mongo@1.4.2
mongo-dev-server@1.1.0
mongo-id@1.0.6
msavin:jetsetter@4.0.0
msavin:mongol@4.0.1
npm-bcrypt@0.9.3
npm-mongo@2.2.34
observe-sequence@1.0.16
ordered-dict@1.1.0
percolate:migrations@1.0.2
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.10.1
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.8
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.0.12
sacha:spin@2.3.1
server-render@0.3.0
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.3.1
shim-common@0.1.0
socket-stream-client@0.1.0
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.0
standard-minifier-js@2.3.1
supermongol@2.0.0
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.2.0
webapp@1.5.0
webapp-hashing@1.0.9

**Comment by msavin** [comment]
It might be a code execution issue. Can you try to move meteortoys to the upper portion of your package list?

**Comment by msavin** [comment]
Closing this out - please try the suggested fix and new version. If the issue persists, just let me know.
