### ISSUE TITLE
Update aldeed:collection2 dependency to 3.0.0

### ISSUE THREAD

**Issue by ghost** [msavin/Mongol#156]
I have the latest version of collection2 (3.0.0) installed in my project, but there is a dependency on version 2.3.2 in the latest version of mongol; the latest version it will let me install because of this is 0.5.5. I assume this is because there was no dependency on collection2 in that version? Any chance the dependencies could be updated?

**Comment by yanickrochon** [comment]
Just ran into this too. Please update as the former package _is_ marked as deprecated.

**Comment by steven-tib** [comment]
Same issue here with the dependency to 2.3.2

**Comment by ghost** [comment]
I have a PR pending but it seems that this package might be abandoned.

**Comment by fillipefeitosa** [comment]
@jeffm24 
Your PR seems to solve the problem. Any answers from the maintainer? 
Is there another solution similar to Mongol?

**Comment by msavin** [comment]
And.. done! 

I tested on todos and a regular starter app.. and would appreciate a further confirmation that its working.
