### ISSUE TITLE
Mongol not showing when i press Control + M

### ISSUE THREAD

**Issue by molleman** [msavin/Mongol#20]
Hey,

i just added the package

when i press Control + M

Nothing is displayed, the scripts are loaded,

Any ideas?

**Comment by msavin** [comment]
Do you have mousetrap or any key bindings? Also, are you focusing on the web page when you press or, or the browsing application?

**Comment by molleman** [comment]
No i don't have mousetrap or any key bindings

I have tested in chrome, safari and firefox

Give you a laugh

I have tried 

Control and m
Control and M
Control = M
Control shift m
Control shift M

and so on so forth.

I'm using matteodem/meteor-boilerplate and a few other packages, but I don't see how they would interfere.

Is there anyway to activate it through the console?

**Comment by msavin** [comment]
Weird man. OS X right? You sure you're not using the command key? Haha

This should do it:

Session.set("Mongol_settings_display", true);

The control + m just flip the value of that variable.

**Comment by molleman** [comment]
Yeah OS X , its safe to say i tried every combination in the past 15mins possible with the key M... nothing worked!! :-)

Yup Session.set("Mongol_settings_display", true); worked a treat

Cheers

**Comment by msavin** [comment]
Glad that worked for you. Strange issue though. Could you share any more details about your system configuration? Just want to make sure that Mongol works well for everyone who installs it.

**Comment by JackAdams** [comment]
Session.set("Mongol_settings_display", true)

**Comment by mbabauer** [comment]
I am also having this same issue, and also on OS X.  I looked at my Keyboard setup in Settings and saw no Ctrl-M shortcuts defined there.  I also searched Google, but found nothing.  I know when I hit Ctrl-M my mouse pointer dissapears, so something it happening, just not sure what.

**Comment by JackAdams** [comment]
I was able to reproduce the bug and #21 fixes it.
