### ISSUE TITLE
Issue inserting and updating documents with SimpleSchema

### ISSUE THREAD

**Issue by msavin** [msavin/Mongol#23]
Returns the following error when trying to insert or update documents: 

I20150226-13:31:39.137(-8)? Exception while invoking method 'Mongol_insert' ReferenceError: SimpleSchema is not defined
I20150226-13:31:39.137(-8)?     at Meteor.methods.Mongol_insert (packages/msavin:mongol/server/methods.js:84)
I20150226-13:31:39.138(-8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599)
I20150226-13:31:39.138(-8)?     at packages/ddp/livedata_server.js:648
I20150226-13:31:39.138(-8)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20150226-13:31:39.138(-8)?     at packages/ddp/livedata_server.js:647
I20150226-13:31:39.138(-8)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20150226-13:31:39.139(-8)?     at _.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646)
I20150226-13:31:39.139(-8)?     at packages/ddp/livedata_server.js:546

Commented out the code to publish the new changes. 

cc: @JackAdams @krawalli

**Comment by krawalli** [comment]
yeah thats mine. See PR (and chat)
