### ISSUE TITLE
Does not work with Meteor.users

### ISSUE THREAD

**Issue by todda00** [msavin/Mongol#3]
I have this working for the collections I have created, but it does not work for Meteor.users, throws this client error.

```
Error: Exception in template helper:
TypeError: Cannot read property 'find' of undefined
    at String.Template.MongoInspector_collection.helpers.collectionCount (collection.js:43)
    at bindDataContext (lookup.js:26)
    at Blaze._wrapCatchingExceptions (exceptions.js:51)
    at Object.Spacebars.call (spacebars-runtime.js:130)
    at Template.MongoInspector_collection.HTML.DIV.HTML.DIV.Blaze.If.HTML.SPAN.class (collection.html:15)
    at null.<anonymous> (builtins.js:49)
    at view.js:179
    at Object.Blaze._withCurrentView (view.js:414)
    at viewAutorun (view.js:178)
    at Tracker.Computation._compute (tracker.js:263)
```

I can run Meteor.users.find({}) in the browser console without issue.

**Comment by kevohagan** [comment]
What did you list in your collections field when setting Mongol in your Session?

You should list 

```
'collections': ['Users']
and not
'collections': ['Meteor.users']

```

**Comment by delay** [comment]
I have also tried both 
'collections': ['Users']
and 
'collections': ['Meteor.users']
and neither works.  I know I have at least some users in my test system as I can login with no problem.

Uncaught TypeError: Cannot read property 'find' of undefinedcollection.js:16 Template.MongoInspector_collection.events.clicktemplate.js:278 (anonymous function)view.js:760 (anonymous function)view.js:414 Blaze._withCurrentViewview.js:759 (anonymous function)events.js:47 (anonymous function)jquery.js:4665 jQuery.event.dispatchjquery.js:4333 elemData.handle

**Comment by kevohagan** [comment]
Strange.. Well it is working for me! :)

```

Session.set "Mongol",
  'collections': ['Users', 'Events', 'Calendars', 'Messages']
  'display': true,
  'opacity_normal': ".7"
  'opacity_expand': ".9"

```

**Comment by msavin** [comment]
Are you publishing and subscribing to the user collection?

**Comment by todda00** [comment]
Yes, I am subscribing to the Meteor.users collection and have it published. Only difference is I am not initializing the collection myself , as it is initialized by Meteor core. This is not a deal breaker for me, but it might be nice to manage the built in Meteor.Users collection.

I have tried Meteor.users, Meteor.Users, users, Users with the same result. 

Perhaps its a load order, maybe if the package added accounts-base to the api.use array it would be available at the time the client code needs to run?

**Comment by delay** [comment]
It's still not working for me either.  I didn't have it subscribed to previously.  I tried subscribing to it a few ways but still no luck.  It works great for all of the collections I created on my own.  I just can't get it to read the Meteor.users collection (which was setup in accounts-base, accounts-password for me).  I am a bit new to meteor so I am probably making some dumb mistake.  If you could tell me the server, client code you are using to expose the Meteor.users collection to mongol that would be great.

Anyway it's a really awesome package and is working great for my other collections, it will help speed up my development immensely!  Thanks so much for creating it!

**Comment by msavin** [comment]
I think the issue here is that users is a namespaced collection. The fix for that is coming soon :)

**Comment by steph643** [comment]
Same issue here.

**Comment by jindrichbartek** [comment]
Also we have same problem in our project.

**Comment by JackAdams** [comment]
#17 fixes this.

**Comment by msavin** [comment]
Can confirm - but would appreciate if you guys would update and let us know how its working

**Comment by delay** [comment]
Works for me!  Thanks so much!  Also for anyone reading this and looking to get the server side meteor.users collection for testing purposes to show up in mongol. http://stackoverflow.com/questions/25198683/subscribing-to-meteor-users-collection

**Comment by jindrichbartek** [comment]
Reading works now, and that is super. But when I'm trying to update current user doc or Account, it throws errors on server. edit: I found out, that although errors, updates working. Thanks!

```
I20150303-21:11:02.774(1)? Exception while invoking method 'Mongol_update' Error: Did not check() all arguments during call to 'Mongol_update'
I20150303-21:11:02.774(1)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150303-21:11:02.774(1)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150303-21:11:02.774(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150303-21:11:02.775(1)?     at packages/ddp/livedata_server.js:648:1
I20150303-21:11:02.775(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150303-21:11:02.775(1)?     at packages/ddp/livedata_server.js:647:1
I20150303-21:11:02.775(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150303-21:11:02.775(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150303-21:11:02.775(1)?     at packages/ddp/livedata_server.js:546:1

```

**Comment by JackAdams** [comment]
@jindrichbartek yes, this is #39. I'll be looking to get a fix ready in the next 24 hours or so.

**Comment by JackAdams** [comment]
@jindrichbartek this is fixed in the latest release

**Comment by MasterJames** [comment]
I'm thinking the error might occur when used without template helpers?
I'll look for a way to tell it what to attach it's display too, as it will be invisible in my package, but since I only get the error. I guess it's not for me.

```
Exception in template helper: TypeError: Cannot read property 'find' of undefined
at String.Template.MongoInspector_documentViewer.helpers.active (http://localhost:3000/packages/msavin_mongol.js?f101ffe56d870811294f4958c4008a18533a1eda:572:41)
at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:2986:16
at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1650:16
at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3038:66
at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3671:12)
at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3037:27
at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?1aedcc2aa3ae9ff5d860d73516110cedd77c033e:167:18)
at http://localhost:3000/packages/msavin_mongol.js?f101ffe56d870811294f4958c4008a18533a1eda:466:22
at null.<anonymous> (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:2674:44)
at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1872:20
```

Maybe also triggered if you're using a different router?
