### ISSUE TITLE
Mongol only shows account and users

### ISSUE THREAD

**Issue by jakobrosenberg** [msavin/Mongol#30]
I have multiple active, working subscriptions, but Mongol doesn't show them. Am I doing something wrong?

**Comment by msavin** [comment]
can you please send us a list of the packages you're using?

**Comment by krawalli** [comment]
..and have a look here: https://github.com/msavin/MongoInspector/issues/17

Maybe the same problem

**Comment by jakobrosenberg** [comment]
accounts-base@1.1.3
accounts-facebook@1.0.3
accounts-oauth@1.1.3
accounts-password@1.0.6
accounts-ui@1.1.4
accounts-ui-unstyled@1.1.6
amplify@1.0.0
application-configuration@1.0.4
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
clinical:nightwatch@1.6.0
coffeescript@1.0.5
cramhead:cloudinary@0.9.3
daniel:build-fetcher@0.2.0
dburles:mongo-collection-instances@0.3.1
ddp@1.0.14
deps@1.0.6
ejson@1.0.5
email@1.0.5
facebook@1.1.3
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
handlebars@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
joshowens:accounts-entry@1.0.3
joshowens:simple-form@0.2.2
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
lepozepo:streams@0.2.0
less@1.0.12
livedata@1.0.12
localstorage@1.0.2
logging@1.0.6
manuelschoebel:less-bootstrap-3@0.0.1
matb33:collection-hooks@0.7.9
meteor@1.1.4
meteor-platform@1.2.1
meteorhacks:kadira@2.19.6
meteorhacks:meteorx@1.3.1
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
mongo@1.0.11
mongo-livedata@1.0.7
mquandalle:harmony@0.0.41
mquandalle:jade@0.4.1
mrt:underscore-string-latest@2.3.3
msavin:mongol@0.5.2
npm-bcrypt@0.7.7
oauth@1.1.3
oauth2@1.1.2
observe-sequence@1.0.4
ordered-dict@1.0.2
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
schnie:uploader@2.0.3
service-configuration@1.0.3
session@1.0.5
sha@1.0.2
softwarerero:accounts-t9n@1.0.3
spacebars@1.0.5
spacebars-compiler@1.0.4
srp@1.0.2
standard-app-packages@1.0.4
templating@1.0.11
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
velocity:core@0.4.5
velocity:html-reporter@0.4.2
waitingkuo:jade@0.2.6
webapp@1.1.6
webapp-hashing@1.0.2

**Comment by jakobrosenberg** [comment]
I had a look and tried the fix, but it did not work.

Also, of all my collections, the user collection is the only one I see. His/her problem was the exact opposite.

**Comment by jakobrosenberg** [comment]
Finally fixed. I had to refresh the browser after moving mongol to the top of packages. It wasn't enough to let Meteor update the page dynamically after compiling.

Thanks for your help. :)

**Comment by msavin** [comment]
Makes sense - the hot refresh must have preserved the collection list in the Session variable. Thanks for reporting it, good to know its still an issue. I'll submit this to @dburles and add a heads up to the readme
