### ISSUE TITLE
Can't export package variables with debugOnly:true

### ISSUE THREAD

**Issue by JackAdams** [msavin/Mongol#34]
This is not a Mongol specific issue, but it has an effect on what I want to do to.

I'd like to be able to export `Mongol`, so that users can have a little API to modify Mongol's behaviour. e.g. 

```
Mongol.beforeInsert = function() { ... };
Mongol.hideCollection("posts");
```

But whether we want to or not, we can't export `Mongol`, because in debug mode, the only thing that gets exported to the global scope is `Packages['msavin:Mongol'].Mongol` but not plain `Mongol`.  So we _can_ provide an API if devs are willing to interact with _that_ object.

We could do it through dedicated session keys, which has the advantage that devs don't really have to think about development/production environments -- just drop `Session.set('Mongol_hideCollections',['posts','comments'])` into the code and forget about it. Of course there will be a few random Session keys in production apps that do nothing, but that's not a big deal.

Thoughts?

**Comment by msavin** [comment]
I'm in favor of just using the Session variable just because its fast, familiar and simple. You can just drop it anywhere without worrying about much. In the next SessonInspector, I will also be hiding any session variable that begins with Mongol_.

**Comment by JackAdams** [comment]
Yep, that's do-able. It's just a little more challenging to expose an api where Mongol's users can call methods using Session (e.g. proposed solution to #28) -- but not impossible.
