### ISSUE TITLE
Doesn't seem to work with the Collection-Hooks package

### ISSUE THREAD

**Issue by Dsyko** [msavin/Mongol#35]
We are using the [collection-hooks package](https://atmospherejs.com/matb33/collection-hooks) and after adding Mongol the hooks are no longer defined on the collections.

**Comment by Dsyko** [comment]
Actually, looks like I was on an older version (0.7.5) Upgrading to the newest collection-hooks seems to have fixed the issue :)

**Comment by JackAdams** [comment]
Cool. Glad to hear that.
