### ISSUE TITLE
Mongol prevents Accounts-UI from working normally.

### ISSUE THREAD

**Issue by czbaker** [msavin/Mongol#36]
Not sure if this is actually a bug, but if you have Mongol visible/open, it prevents other Accounts-UI dialogs from working.

I had Mongol showing, tried to login/create a user in my app using the normal dialog on my app's navbar and it kept rejecting any attempts, citing 'invalid email'.  This apparently occurs when there are multiple instances of {{> loginButtons }} on one page, or something.

**Comment by JackAdams** [comment]
`meteor update` -- the newest releases of Mongol don't have the extra `{{> loginButtons}}`.

**Comment by msavin** [comment]
Assuming this will work. If not, let us know. Thanks for using Mongol!
