### ISSUE TITLE
listing active subscription

### ISSUE THREAD

**Issue by krawalli** [msavin/Mongol#37]
what about having also a list with active subscriptions?

**Comment by msavin** [comment]
Have it ready- launching it at 1k downloads

**Comment by krawalli** [comment]
you want me to write a download bot? :)

**Comment by msavin** [comment]
Let's go low tech for this one. Shouting from roof tops will do :)

**Comment by grigio** [comment]
+1 If you "lazy load" the subscriptions when a Template is created you need to type `Meteor.default_connection._subscriptions` to see what's going on :)

**Comment by msavin** [comment]
Yeah that's the plan. I'm planning to use object.observe to see how it's changing as well. I'm wondering if I should use a polyfill or fallback to 3 second polling if the developers browser doesn't support it.

**Comment by krawalli** [comment]
btw: _grats_ for being two times in row in atmospheres weekly top 10.

Go for number three!

**Comment by msavin** [comment]
Hmm maybe you're right. I just feel it's too soon for a marketing push

**Comment by grigio** [comment]
I think 3s polling is acceptable, so why is this closed?

**Comment by msavin** [comment]
I wonder if we should build an Object.observe polyfill for Meteor.js, because SessionInspector will need this too. That way we don't have a bunch of things polling at the same time.

**Comment by msavin** [comment]
Thanks @krawalli 

Let's get the bugs out, then launch 1.0 with the subscription watcher!

**Comment by msavin** [comment]
We can market it as a "make it reactive" package. Not every part of Meteor is reactive, and this can be used to tweak that as needed.

**Comment by msavin** [comment]
@krawalli "meteor update" :hamster:
