### ISSUE TITLE
Suggestion: remove display none on by default on small screens

### ISSUE THREAD

**Issue by kevohagan** [msavin/Mongol#4]
Im developping a mobile app and in my setup I use a small screen by default , and #MongoInspector has display:none on screens <768px.

woudl be nice to be able to initiate that on Session.set Mongol

Love the package!! 

This is great to check you pub/sub on different pages!!

**Comment by fungilation** [comment]
I second this, it should be a configurable option. A use case would be in dev, I can use a mobile width (320) but make it very tall so there's still space for Mongol at the bottom.

And yes, cool package! I've been using http://genghisapp.com/, this would be a better inline replacement.

**Comment by msavin** [comment]
Since we're using hot keys, I took the responsive thing off. Enjoy!
