### ISSUE TITLE
Issues with aldeed:simple-schema

### ISSUE THREAD

**Issue by jlynch80** [msavin/Mongol#40]
I get the error "TypeError: Object [object Object] has no method 'attachSchema'" attaching to Meteor.user while using aldeed:simple-schema and msavin:mongol together.

**Comment by JackAdams** [comment]
Ah yes... namespaced collections.  That'll happen.  I'll give it some thought -- there should be a fix for it.

**Comment by JackAdams** [comment]
I haven't been able to reproduce this yet. Can I see a list of the packages you're using? If I can reproduce it, I'm pretty sure a fix will be possible.

**Comment by jlynch80** [comment]
here are the packages i am using (from https://github.com/Differential/meteor-boilerplate):

accounts-password
alanning:roles
aldeed:autoform
aldeed:collection2
anti:fake
cmather:handlebars-server
cunneen:mailgun
dburles:collection-helpers
dburles:factory
iron:router
less
matb33:collection-hooks
meteor-platform
mrt:moment
mrt:underscore-string-latest
reywood:publish-composite
useraccounts:bootstrap
yasinuslu:blaze-meta
zimme:iron-router-active
msavin:mongol

**Comment by JackAdams** [comment]
Thanks, Justin.  I'll see if I can identify the package that Mongol is fighting with later this evening.  Hopefully there will be a fix we can roll out soon.

**Comment by JackAdams** [comment]
Good news.  I was able to reproduce and fix this.  PR #38 has the fix, which I hope will be included in the next release.  Thanks for sending that package list, Justin.  It made solving this issue a lot quicker.
