### ISSUE TITLE
Session Inspector showing Mongol sessions

### ISSUE THREAD

**Issue by Schonne** [msavin/Mongol#42]
I like your Session Inspector, but it shows the Mongol sessions in it. 
![screen shot 2015-03-05 at 12 00 32 am](https://cloud.githubusercontent.com/assets/3167572/6499517/b84c4132-c2ca-11e4-9826-e4fab3d8a650.png)

Can we disable this or prevent Session Inspector from showing these? Better yet: wrap Session Inspector into Mongol!

**Comment by JackAdams** [comment]
These are good ideas.  I believe that @msavin is very much on board with them.  Watch this space.  :-)

**Comment by msavin** [comment]
Indeed - revamping SessionInspector is the next thing after Mongol hits 1.0.

**Comment by msavin** [comment]
Fixed , meteor update ftw :)
