### ISSUE TITLE
problem with "Tabular table" on Meteor.users?

### ISSUE THREAD

**Issue by thearabbit** [msavin/Mongol#43]
I install `tabular table` package

``` js
TabularTable.User = new Tabular.Table({
    name: "UserList",
    collection: Meteor.users,
    columns: [
        {data: "username", title: "User Name"},
        {
            title: '<i class="fa fa-bars"></i>',
            tmpl: Meteor.isClient && Template.userAction
        }
    ]
});
// Work fine
```

But when install `mongol`, it is error on this.

**Comment by msavin** [comment]
Thanks for sharing. What's the error?

**Comment by richsilv** [comment]
I have the same problem (I assume):

> W20150310-16:48:02.538(0)? (STDERR) Error: Tabular.Table options must specify collection
> W20150310-16:48:02.539(0)? (STDERR)     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
> W20150310-16:48:02.539(0)? (STDERR)     at app/both/tabular/tabular.js:5:23
> W20150310-16:48:02.539(0)? (STDERR)     at app/both/tabular/tabular.js:41:3
> W20150310-16:48:02.539(0)? (STDERR)     at /home/richard/Meteor/SVS-Testing/.meteor/local/build/programs/server/boot.js:205:10
> W20150310-16:48:02.539(0)? (STDERR)     at Array.forEach (native)
> W20150310-16:48:02.539(0)? (STDERR)     at Function._.each._.forEach (/home/richard/.meteor/packages/meteor-tool/.1.0.41.1m2qlob++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
> W20150310-16:48:02.540(0)? (STDERR)     at /home/richard/Meteor/SVS-Testing/.meteor/local/build/programs/server/boot.js:116:5

**Comment by richsilv** [comment]
To clarify, I'm using `aldeed:tabular` to show a table of users, passing in the `Meteor.users` collection.  it works perfectly without Mongol, but throws the error above on the server once it's added.  I've also tried passing in `Mongo.Collection.get('users')` instead, with no joy.

**Comment by msavin** [comment]
Does it work if you use a collection other than users? 

I've never worked with either of these, I think only @krawalii or @JackAdams  could fix it

**Comment by JackAdams** [comment]
I'll take a look at it in a few hours' time.

**Comment by JackAdams** [comment]
I couldn't reproduce this one, but it's definitely to do with the auto-detection of collections where Mongol wraps the `Mongo.Collection` API.  Try putting `aldeed:tabular` before/after `msavin:mongol` in the `.packages` file and see if that makes a difference. Let us know if it does.

**Comment by msavin** [comment]
@JackAdams Should we wrap the collections on the client side only? and then the people who have issues there.. we can tell them to custom list their collections.

**Comment by thearabbit** [comment]
Now it work  fine, when I install `msavin:mongol` before `aldeed:tabular`.

**Comment by JackAdams** [comment]
@yuomtheara this is really helpful information. Thanks!

**Comment by richsilv** [comment]
Apologies for the delay, I can confirm that putting mongol before tabular in the package load order resovles this for me. Thanks.

**Comment by JackAdams** [comment]
Thanks for confirming that, @richsilv.  That's good to know.

**Comment by msavin** [comment]
:+1:

**Comment by kalubunda** [comment]
Hey my name is mandla i just wanna ask how to display data in a tabular from joins collections.
i joined two collections and want to display the data in a tabular form. thank you
