### ISSUE TITLE
Explicitly declare what collections you would like to see

### ISSUE THREAD

**Issue by jasonxeno** [msavin/Mongol#44]
It seems in the newest version the ability to explicitly declare what collections you would like to see in Mongol was deprecated due to the new functionality in #9. The problem is that I found that feature useful as I have 40 collections and only wanted to keep track of the main 5 collections I have. Is it possible to add that feature back as an option?

**Comment by msavin** [comment]
Sounds right, I'll bring it back

**Comment by msavin** [comment]
Fixed, please update and let me know if you have any issues
