### ISSUE TITLE
CSS styles don't take "print" into account, Mongol window always prints

### ISSUE THREAD

**Issue by ssteinerx** [msavin/Mongol#45]
A simple '@media print' section that set #Mongol to hidden should do the trick...

**Comment by msavin** [comment]
But there could be a case where you'd want to print it (i.e. to compare JSON to results). Does it print even when its disabled?

**Comment by ssteinerx** [comment]
No, it only prints when it's open.   No big deal, I'll just modify my own CSS if you think printing it might be useful to have it print which I hadn't considered (I'm printing forms, so I'd never need it to print).
