### ISSUE TITLE
Search feature in Mongol

### ISSUE THREAD

**Issue by WilliamHua** [msavin/Mongol#47]
Is it possible to have some kind of querying feature in Mongol so that if your database is thousands of documents large, you can still easily find what you're looking for?

**Comment by msavin** [comment]
The thing is that Mongol is designed to work with MiniMongo (your client side documents). I guess its possible to do, but I don't think there's a use case where the client would by syncing 1000 documents to the client.

**Comment by WilliamHua** [comment]
Ah I see I completely forgot. I was thinking it would take the place of something like PHPMyAdmin for MySQL databases
