### ISSUE TITLE
Conflict with ongoworks:security package

### ISSUE THREAD

**Issue by ChenRoth-old** [msavin/Mongol#49]
i've just added the mongol package, while having the security package in the project

the app crashes with this error:

```
Error: The collections argument must be a Mongo.Collection instance or an array of them
W20150311-11:02:18.428(2)? (STDERR)     at SecurityRuleConstructor.Security.Rule.collections (packages/ongoworks:security/security-api.js:45:1)
W20150311-11:02:18.428(2)? (STDERR)     at [object Object].Mongo.Collection.permit (packages/ongoworks:security/security-api.js:101:1)
```

this is caused when I'm trying to apply permissions to the Meteor users collection

any thoughts?

**Comment by JackAdams** [comment]
I haven't reproduced this one yet, but then ... I haven't tried much more than adding the package and playing around with my `.packages` file.  From what you've said, I'm guessing I'd also need to try applying permissions to the Meteor users collection to reproduce the error.  I'm pretty sure this error is to do with the auto-detection of collections where Mongol wraps the `Mongo.Collection` API.  Try putting `ongoworks:security` before/after `msavin:mongol` in the `.packages` file and see if that makes a difference. Let us know if it does.

**Comment by ChenRoth-old** [comment]
putting msavin:mongol before security causes this error:

```
W20150311-15:54:24.012(2)? (STDERR) TypeError: Object [object Object] has no method 'permit'
W20150311-15:54:24.012(2)? (STDERR)     at app/server/permissions.js:20:7
W20150311-15:54:24.012(2)? (STDERR)     at app/server/permissions.js:25:3
```

where the referenced line is something along:

```
Meteor.users.permit('update').exceptProps( *redacted* ).apply();
```

so this would be a simple reproduction to work with

**Comment by JackAdams** [comment]
Thanks @ChenRoth I'll take another look tonight, but this is a tricky one if it produces an error for both configurations of the packages (relative to each other) in the `.packages` files.

**Comment by rclai** [comment]
Does `.permit()` only not exist on `Meteor.users`?

**Comment by msavin** [comment]
Going to close this since its not really an issue with Mongol
