### ISSUE TITLE
Scrollbars?

### ISSUE THREAD

**Issue by rclai** [msavin/Mongol#50]
It looks really nice man.

Why do you have [this](https://github.com/msavin/Mongol/blob/4eb0df3775bf13e71dabcb7976513b46a9cc0e25/packages/msavin:mongol/client/style/Mongol.css#L24) set to `scroll`? Shouldn't it be `hidden`? I'm getting an empty scrollbar on the UI and I'm using Chrome (on a Ubuntu 14.04 machine).

**Comment by msavin** [comment]
Some people have so many collections that it extends beyond the window. I'll try to hide the actual scrollbar.

**Comment by rclai** [comment]
Oh I see. How about using one of those fancy scrollbar plugins, like [this one](https://github.com/malihu/malihu-custom-scrollbar-plugin). That would be hot.

**Comment by maggo** [comment]
If you set this to `overflow: auto;` it will display scrollbars only when content is actually overflowing

**Comment by msavin** [comment]
Good point - I just pushed it and it'll be in the next update tomorrow.
