### ISSUE TITLE
Can't use "duplicate" option with custom _id?

### ISSUE THREAD

**Issue by thearabbit** [msavin/Mongol#51]
I insert doc with custom `_id` like this:

``` javascript
{
  "_id": "002",
  "name": "Tehara",
  "gender": "M",
  "address": "Banteay Meanchey",
  "telephone": "070"
}
```

and then i insert the new one by `duplicate` btn, but can't it show error duplicating.

**Comment by JackAdams** [comment]
I'll look into this soon.

**Comment by JackAdams** [comment]
Is this still happening?  I was unable to replicate this issue.

**Comment by krawalli** [comment]
I think you need to add it at least two times

**Comment by msavin** [comment]
and shake your computer left to right while you do it :P

**Comment by krawalli** [comment]
see issue #66 - almost the same cause i guess

**Comment by JackAdams** [comment]
I'm not actually clear what the issue is here, because the duplicate button works perfectly well with any `_id`, custom or not.  At least, when I've tested it, it does.

**Comment by msavin** [comment]
@yuomtheara can you give some more details about this issue? Otherwise I'll have to close the issue as what you're describing doesn't seem to be a problem

**Comment by rabbittc** [comment]
if my `_id` field is the custom value ("001"), don't auto value (object id).
So i can't use `duplicate` option.

**Comment by JackAdams** [comment]
@rabbittc I just tried duplicating a document with an _id value of "001" and it worked fine.  Any chance of putting a minimal repro of your issue on Meteorpad?

**Comment by rabbittc** [comment]
Ok I will try again.
