### ISSUE TITLE
Create ability to add other tabs so we can build third-party packages to extend mongol

### ISSUE THREAD

**Issue by rclai** [msavin/Mongol#52]
For example, I want to be able to add my [ddp inspector](https://github.com/rclai/meteor-ddp-inspector) in a new tab on mongol to show all the ddp activity that happens. 

And then you can create another third-party package (like the [other one you have](https://github.com/msavin/SessionInspector)) for another tab that shows all the Sessions.

Some other guy could build another package to give you the server's memory usage/CPU load, etc.

What do you think?

**Comment by msavin** [comment]
I like that idea. Besides DDP inspection, what else would you like to see in Mongol? I'm thinking to just build in a DDP watcher into Mongol.

**Comment by rclai** [comment]
I think that's a good start. Also, I think that being able to resize the panel would be nice. But essentially what I was getting at in the grand scheme of things is that there is a need to consolidate all dev tools in one place somehow, and I thought Mongol was a good place. It's messy having all these different dev packages all over the place, Slava's xray button at the top right, your session inspector on the bottom right, my ddp inspector on the bottom left, etc.

**Comment by msavin** [comment]
Yeah we've had some packages that extend Mongol, so I've been thinking about it. You'll see some new stuff soon :)

**Comment by JackAdams** [comment]
I agree that mongol is the best kind of interface I've seen to consolidate dev tools. We have talked about a plugin system, where each plugin gets its own tab on Mongol. @msavin -- I can start working on this in a couple of weeks' time.

**Comment by rclai** [comment]
So..  What happened here?

**Comment by JackAdams** [comment]
@msavin are you still open to the idea of a plugin system?

**Comment by msavin** [comment]
I'm trying out different designs / concepts - going to announce my solution in a couple of weeks

**Comment by rclai** [comment]
Okie doaks.
