### ISSUE TITLE
Refused to load the image 'https://www.paypalobjects.com/en_US/i/scr/pixel.gif'

### ISSUE THREAD

**Issue by sunkay** [msavin/Mongol#53]
I have browser-policy package and it gives me the following error. I would rather not add this to allow in my file... Is it possible to add this to the package assets?

Refused to load the image 'https://www.paypalobjects.com/en_US/i/scr/pixel.gif' because it violates the following Content Security Policy directive: "img-src data: ...

**Comment by bensmeets** [comment]
+1 :)

**Comment by rasschaert** [comment]
The uBlock plugin in Chrome also blocks the PayPal tracking pixel.

The console logs `GET https://www.paypalobjects.com/en_US/i/scr/pixel.gif net::ERR_BLOCKED_BY_CLIENT`  every time I open Mongol.

Please remove it :+1:

**Comment by msavin** [comment]
Ok I'll drop the pixel next version

**Comment by msavin** [comment]
Gone
