### ISSUE TITLE
"This application contains Mongol" is annoying

### ISSUE THREAD

**Issue by outluch** [msavin/Mongol#55]
Thanks for awesome tool, but is it so nessesary to log this?? 
I like clean console and want see there errors only, or my debug info. Maybe some parameter in with Session would turn this off?

**Comment by msavin** [comment]
I've heard that one before. My goal is to educate just so people don't deploy it to production.  But maybe better to leave that responsibility to main developer.

**Comment by rhyslbw** [comment]
:+1: 

I was going to suggest using `debugOnly: true` in the package description, but it's already there. What am I missing?

**Comment by msavin** [comment]
The two issues are people deploying in debug, or not knowing what debugOnly is.

**Comment by rhyslbw** [comment]
In that case I'd just remove the warning, as you have a control in place :smile:

**Comment by outluch** [comment]
My 2 arguements here: When you deploy with `-debug` you know what you do, because it is not default, you need to use parameter. And if some other developer decides to educate me too, he will steal just another line from my console. Vertical space is quite expensive. 
Some option like `'Mongol_settings_logging_off'` needed imho.

**Comment by msavin** [comment]
Agree with you on vertical space; that's why I built Mongol in the first place. That console bar just eats away too much space. I think the best way to move forward is to just include details about this in the documentation.

**Comment by Maxhodges** [comment]
I actually want to deploy it to an app which we are going to demo, but can't just host locally for important reasons. is there an easy way to deploy it? present it seems like it's being auto-removed

cheers!

**Comment by msavin** [comment]
Try deploying or building with "--debug", it will build the app on the same way it runs locally
