### ISSUE TITLE
Can't copy the _id

### ISSUE THREAD

**Issue by mplatts** [msavin/Mongol#56]
Kind of a minor thing - I like to copy and paste the `_id` of things - it seems after I updated I can't do this any more (have to click "Update" then I can copy it)

(Great package btw)

**Comment by JackAdams** [comment]
Whoa... you're right.  This is my fault.  I'll fix it in the next day or two.

**Comment by msavin** [comment]
@JackAdams I semi-took care of it with a new PR. The _id field cannot be edited as indicated by the cursor, but we should let people select ID. Maybe if they try to edit it, we can throw an alert "hey .. no, stop it!"

**Comment by JackAdams** [comment]
PR #61 fixes this issue

**Comment by msavin** [comment]
Closing this issue. @mplatts please update and let us know if the issue continues

**Comment by mplatts** [comment]
@JackAdams @msavin  it's kind of fixed. I click the _id value and it becomes highlighted. But if I hit `cmd-c` to copy it doesn't copy. Right clicking and clicking "Copy" works... but yeah... `cmd-c` is the way I'd like to copy.

**Comment by JackAdams** [comment]
Oh shoot... yes, that's my bad again.  I'll fix this soon.

**Comment by mplatts** [comment]
:+1: no rush ha

**Comment by JackAdams** [comment]
All right, just released `editable-json` 0.3.13.  That should fix it @msavin.

**Comment by JackAdams** [comment]
This is fixed in the latest releases of the `editable-json` package.  Just needs merging.  :-)
