### ISSUE TITLE
Configure your GitHub username :)

### ISSUE THREAD

**Issue by dandv** [msavin/Mongol#59]
[Most recent commits](https://github.com/msavin/Mongol/commits/master) appear to come from "Main". 

```
git config --global user.name "Max Savin"
git config --global user.email "msavin@me.com"
git config --global github.user msavin
```

PS: nice seeing you at the Meteor meetups lately. Have you moved to the Bay Area? https://github.com/msavin and https://www.linkedin.com/in/msavin say "New York".

**Comment by msavin** [comment]
Haha thanks man. 

I'm just checking it out - heading back to New York tomorrow. Feels like I've seen around New York before.
