### ISSUE TITLE
<pre> background-color

### ISSUE THREAD

**Issue by rklaeboe** [msavin/Mongol#6]
Solved problem with pre background-color being white by adding:
# MongoInspector pre {background-color: #222222;}

Could perhaps be specified as part of the Session.set
Nice tool !

**Comment by dan335** [comment]
The background is white for me also which makes the text hard to read.

**Comment by msavin** [comment]
This is a bug that I think people using Bootstrap / Material have experienced. Can you update and see what it looks like now? A screen shot would be appreciated!

**Comment by rklaeboe** [comment]
OK now !

**Comment by rklaeboe** [comment]
Here is the screenshot

Ronny Klæboe (Dr.Philos.)

Sponstuveien 49

NO1263 Oslo

Norway

r@klaeboe.info

Fra: Max Savin [mailto:notifications@github.com] 
Sendt: 23. februar 2015 01:50
Til: msavin/Mongol
Kopi: Ronny Klæboe
Emne: Re: [Mongol] <pre> background-color (#6)

This is a bug that I think people using Bootstrap / Material have experienced. Can you update and see what it looks like now? A screen shot would be appreciated!

**Comment by cschep** [comment]
![screenshot 2015-11-22 14 49 15](https://cloud.githubusercontent.com/assets/9520/11326796/43a8f10e-9128-11e5-829b-0f22720083bc.png)
![screenshot 2015-11-22 14 49 27](https://cloud.githubusercontent.com/assets/9520/11326795/43a84aa6-9128-11e5-91e0-3274319471f2.png)

Hey thanks for a really cool tool. I'm using bootstrap and seeing white text on a white background and I found this rule.. looks like combined CSS from another product that might not be appropriate? Or maybe It's the background-color that's more important. Not sure.. hope it's helpful!
