### ISSUE TITLE
Backup/Restore Tool request?

### ISSUE THREAD

**Issue by thearabbit** [msavin/Mongol#60]
Backup/Restore Tool request?

**Comment by msavin** [comment]
For when you delete documents?

**Comment by krawalli** [comment]
maybe better one would be json import / export.

Nice idea

**Comment by JackAdams** [comment]
Work is starting on a undo/redo system soon.  But that's not what you mean, is it?  You're thinking about backing up and restoring the db.

**Comment by msavin** [comment]
I'm thinking a trash can may be better as its persistent.

ie: 
1. User deletes document
2. Document is removed from its collection and inserted to Mongol_Trash collection, with original collection name and remove date
3. User is able to "restore" recent documents from a Trash tab in Mongol

**Comment by JackAdams** [comment]
Yep.  I see the value in that -- having deleted documents persist in more than just a session variable.  It's just, I'm not sure that devs will appreciate a new collection in their db.  Another possibility is to use the `persistent-session` package.

**Comment by msavin** [comment]
We should find out. No reason why we can't implement a trash can in sessions and offer persistent option, or have it as an optional package. 

PS: I'm considering this from a UI/UX perspective as well as technical.

**Comment by thearabbit** [comment]
Ok, I mean export/import data.

**Comment by msavin** [comment]
@yuomtheara you need to give us better descriptions of your idea :P

**Comment by thearabbit** [comment]
I would like to export/import db like other IDE of sql (PhpMyAdmin, Navicate ...)

**Comment by msavin** [comment]
This sounds like a different tool than Mongol, and I'm definitely considering it. Thanks!
