### ISSUE TITLE
doesnt work with collections from packages?

### ISSUE THREAD

**Issue by dcsan** [msavin/Mongol#62]
tried this out - it only seems to pick up collections defined in the main app, nothing from packages.

is there a way to specify what collections to monitor?

**Comment by msavin** [comment]
My man! How are things in SF? 

What packages are you using? 

Listing collections manually may be the right solution for you: https://github.com/msavin/Mongol/blob/master/documentation/COMPATIBILITY.md

**Comment by dcsan** [comment]
yo, word. fixed by ordering. you should call it a1mongol :)

**Comment by andylash** [comment]
I had the same problem, all my key collections are in packages.  Might want to note this in the README.

**Comment by stivaugoin** [comment]
I had the same problem, but I don't understand where to apply the solution to listing collections manually. Presently I use meteortoys:allthings (free, not premium). It's supposed working with this package too? When I use this code in /lib:

```
Package["meteortoys:allthings"].MeteorToysDict.set("Mongol", {
    collections: ["myCollection"]
});
```

I have this error:

`TypeError: Cannot call method 'set' of undefined`

I think I really don't understand! haha
