### ISSUE TITLE
Idea: See all publications and subscribe on them by clicking on one

### ISSUE THREAD

**Issue by remcoder** [msavin/Mongol#63]
Forgetting to the subscribe to published data (or the other way around) is an easy mistake to make. It would be nice if Mongol could show us a list of publications and allows us to subscribe to them as easy as clicking on them.

Here're some things that might be good place to start:

On the server there is a list of publications, here:

```
Meteor.server.publish_handlers
```

example:

```
{ 
meteor_autoupdate_clientVersions: [Function],
meteor.loginServiceConfiguration': [Function],
favorites: [Function],
favoritesByUser: [Function],
comments: [Function],
commentsByDoc: [Function],
commentsByUser: [Function],
notifications: [Function],
seoByRouteName: [Function],
adminCollection: [Function],
adminAuxCollections: [Function],
adminUsers: [Function],
adminUser: [Function],
'app-data': [Function],
user: [Function],
users: [Function],
admin_collections_Beacons: [Function],
admin_collections_Rooms: [Function],
admin_collections_POIs: [Function],
admin_collections_Themes: [Function],
admin_collections_Users: [Function] }
```

To accommodate handlers that take arguments, a dialog could be presented allowing the user to enter some params.

The function source is accessible via `.toString()` and the arguments could be extracted using [this method used by Angular](http://stackoverflow.com/questions/1007981/how-to-get-function-parameter-names-values-dynamically-from-javascript).

**Comment by msavin** [comment]
This is coming in the Meteor Toy, so I'll close the issue. Thanks for your suggestion!
