### ISSUE TITLE
Need a way to disable the "This application contains Meteor Toys. Learn more: http://meteor.toys" message.

### ISSUE THREAD

**Issue by ljmatkins** [msavin/Mongol#64]
I appreciate the desire to introduce people to meteor.toys -- but now that I've visited the site, I would like to disable the console message so I don't see it whenever my app starts. An explicit configuration parameter or something would be helpful. As it is, I'm not really (yet) using Mongol for much, and seeing this message over and over makes it more likely that I'll just remove the package.

**Comment by tehfailsafe** [comment]
:+1: 

This is really uncool. Littering ever single console for the people who already installed your plugin is unacceptable. This kind of pushyness makes me want to UNjoin the community you are trying to foster.

**Comment by msavin** [comment]
Point taken - just run update and it'll be gone. 

The goal was to educate on Meteor Toys - just in case other team members aren't aware or someone else inherits a code base. The community part there came after. But I'll leave the responsibility up to the developers in charge. 

PS: Once you join, you can't unjoin .

**Comment by tehfailsafe** [comment]
I wouldn't be against something like Kadira's message on meteor startup in the terminal, if other team members aren't aware and run `meteor` they will see it once on startup and that would be it.

I just worked through a bunch or errors in the console and came across this message for the first time after I finally cleared them. Then refreshed a few times and realized it was going to stay there...

**Comment by msavin** [comment]
Good thinking, thanks for the suggestion
