### ISSUE TITLE
Mongol_verify method concern

### ISSUE THREAD

**Issue by sircharleswatson** [msavin/Mongol#65]
I was just looking at some of the source and noticed this:
https://github.com/msavin/Mongol/blob/master/server/methods.js#L10

I'm wondering if it was intentional that the "if" statement has a variable being set in it. It seems as though that should not be the case. Otherwise, it would always be passing rather than actually checking the equality.

**Comment by msavin** [comment]
Ah good point. It's actually not using that method. Maybe it's worth adding though.

**Comment by sircharleswatson** [comment]
oh! I didn't know it wasnt using the method. I was just browsing and saw that it looked odd. :)

I just installed Mongol and JetSetter today and I'm really liking them. Keep up the great work! Bring on the toys!
