### ISSUE TITLE
Collections of Tweets Show Create/Insert Tabs & No Data

### ISSUE THREAD

**Issue by ghost** [msavin/Mongol#69]
There is a paste of an example tweet object @: http://paste.meteor.com/mq7o3wQCZBaYZnK6f
Screenshot attached.
![Uploading 2015-03-29-012149_1920x1080_scrot.png . . .]()

Thanks for the killer package!

Linux version: Mozilla Firefox 36.0.4

**Comment by JackAdams** [comment]
Any repro available for this?  @msavin -- I don't think it's the `editable-json` package (see [here](http://meteorpad.com/pad/AphADo6eR4aiJmNzS/Editable%20JSON%20Example)).

**Comment by msavin** [comment]
@arthax0r can you please update us on this issue?

**Comment by msavin** [comment]
@arthax0r Can you please try running ' Session.set('Mongol_noInlineEditing', true);  ' in the console before opening Mongol? This should disable the Inline JSON editing and may get us closer to the solution.

**Comment by iDoMeteor** [comment]
Just loaded it up, seems to be working good!  I will be putting in some work on this project again soon.. Mongol working great on my current one, editing & all! :)

Thanks for following up!

**Comment by ghost** [comment]
Just loaded it up, seems to be working good! I will be putting in some work on this project again soon.. Mongol working great on my current one, editing & all! :)

Thanks for following up!

**Comment by msavin** [comment]
I'd guess there were some transforms involved. Glad to hear it's working now.
