### ISSUE TITLE
CSS glitches

### ISSUE THREAD

**Issue by lucascurti** [msavin/Mongol#7]
Hi Max!

I see some CSS glitches. Probably, they are conflicts with my App's CSS. 

On the first image the Duplicate and Remove buttons are off. I see this issue in Chrome for MAC but not in Safari.
On the second image, you'll see that text is white when I hit Update button. 

I'll try to troubleshoot these issues and let you know.

![screen shot 2015-02-20 at 12 00 25 am](https://cloud.githubusercontent.com/assets/2811287/6280431/f1f70a34-b893-11e4-962f-7aef3b0a981e.png)
![screen shot 2015-02-20 at 12 00 36 am](https://cloud.githubusercontent.com/assets/2811287/6280430/f1938f36-b893-11e4-9de6-b571288a3008.png)

**Comment by steph643** [comment]
Similar issue here. I got **no left arrow**, so I can not navigate to the previous doc in the collection:

![image](https://cloud.githubusercontent.com/assets/7039479/6283105/c3c63a6c-b8df-11e4-9a15-e2ae3eee8dd7.png)

Also, when I select "Update", all text becomes white:

![image](https://cloud.githubusercontent.com/assets/7039479/6283130/155a8342-b8e0-11e4-94ac-3c441cbb508b.png)

**Comment by steph643** [comment]
Maybe this is linked to this exception I get at load time:

```
debug.js:41 Exception from Tracker afterFlush function: Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.
    at Error (native)
    at Template.MongoInspector.rendered (http://localhost:3000/packages/msavin_mongol.js?558950870b2ec9c51c4caac919a2ca3b3e8b6a76:809:26)
    at http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:3004:22
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:3226:12)
    at fireCallbacks (http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:3000:12)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:3093:5)
    at http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:1733:14
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:2047:12)
    at http://localhost:3000/packages/blaze.js?afacad40717d17641307b75e1f9758d24643138e:1732:15
    at Tracker.flush (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:448:11)
sockjs-0.3.4.js:854 XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=okxdzcysac".
```

**Comment by Digital-Thor** [comment]
Thanks for making this tool.  I'm having similar problems with left button disappearing on Chrome at 100% browser zoom. In Firefox, I get neither left nor right buttons and changing zoom doesn't help. I also inspected the CSS class and it appears that the div is disabled. (Orange box annotations are mine.)

![image](https://cloud.githubusercontent.com/assets/2617288/6312231/bac00726-b926-11e4-8079-d79b3d6f83a9.png)

**Comment by msavin** [comment]
Thanks for letting me know! I will work to resolve these things on Monday. Let me know if you have any other issues.

**Comment by dpastoor** [comment]
bumping as well for the same issue(s) - running on chrome v40.0.2 on osx mavericks

**Comment by msavin** [comment]
I just pushed an update with a potential fix for the code window.. can you let me know if that helped?

**Comment by steph643** [comment]
Here is what I get:
- When I select "Update", all text becomes white but the background now turns black. So this looks like it is fixed.
- Still no left arrow (to navigate through mongo doc)
- This exception:
  `Exception from Tracker afterFlush function: Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.`
  has been replaced by this one:
  `Exception from Tracker recompute function: Error: No such template: Mongol_accountViewer`

**Comment by msavin** [comment]
All these glitches should be resolved. Please let me know if you're still experiencing any after the update. Thanks for letting me know about them!
