### ISSUE TITLE
How to disable/enable this ?

### ISSUE THREAD

**Issue by KrishnaPG** [msavin/Mongol#78]
Not sure if this option is already available, but couldn't deduce it from Readme doc.

Presently pressing Ctrl+M shows this console.

Is there some kind of switch or global variable in the code that would disable/enable this? I would like to turn this on only for my local runs and off other times.

**Comment by msavin** [comment]
Thanks for letting me know. 

What kind of console does it show? Also - what is your OS / Browser?

**Comment by KrishnaPG** [comment]
Well - "console" may be a wrong word, I meant to say the UI as shown below (what ever it is called). Would like to programatically enable/disable the display of this at runtime (e.g. only making this appear to Admin users and not for all users when pressed Ctrl+M)

![image](https://cloud.githubusercontent.com/assets/4610831/7214338/3d4222e0-e5c5-11e4-80c1-24c693bd7252.png)

**Comment by JackAdams** [comment]
Mongol doesn't get included in production builds.  It is only available in your app while you're developing on localhost.

**Comment by KrishnaPG** [comment]
Ok - cool. Thanks for sharing this good work with the world. It is helpful.
