### ISSUE TITLE
Adding new array to doc using update corrupts a date

### ISSUE THREAD

**Issue by dpatte** [msavin/Mongol#79]
My docs have two date fields, Submitted and Updated. If I use mongol and update a doc adding the following: 
"test": ["Line1","Line 2","Line 3"],
and save, the first date is corrupted.
Viewing in Mongol, dates seem to be displayed with an extra space at the end, but after updating, the first date no longer has the extra space and is corrupted when read.

**Comment by dpatte** [comment]
Is it possible that when doing an update using mongol, that the date in a doc is being converted from a Date type to a string type?

**Comment by msavin** [comment]
Yes, looping in @JackAdams since he manages the editable JSON package

**Comment by JackAdams** [comment]
Yes -- it's very possible that dates are being converted to strings, but it sounds like the "update-save" workflow is being used here, not the editable-json.  Still, it's entirely possible that the editable-json is involved in the problem.  I need to give date fields some more attention anyway, so I'll run some tests when I do that.

**Comment by JackAdams** [comment]
Just had a look at the editable-json code -- I think that's what's causing the problem.  I'll work on a fix soon.

**Comment by dpatte** [comment]
Thanks!

**Comment by msavin** [comment]
@JackAdams how far away would a fix be? (I think the solution is to treat dates as a string.) The reason I ask is I'm getting ready to ship Mongol 1.1.0 soon and would like to have this fixed for the update.

**Comment by JackAdams** [comment]
I'll have a look at it later tonight.

**Comment by JackAdams** [comment]
Just checked it. The `editable-json` package is maintaining date types correctly. It's the original update-save workflow that's converting date types to strings.

**Comment by msavin** [comment]
Working on a fix...

**Comment by msavin** [comment]
Fixed in 1.0.90. Let me know if you have any issues.

**Comment by dpatte** [comment]
It looks like it is fixed. Thanks a lot.
I don't seem to be able to use Mongol to fix the date fields that were originally corrupted, but I can use the Mongo command line for that of course.

**Comment by msavin** [comment]
It should parse them back as a date, unless something else was changed about them and they no longer parse as a date. Thanks for confirming it works for you.

**Comment by dpatte** [comment]
Fixing the corrupted dates:
If I use the green fields, it doesn't seem to work.
It does work if I use update/save but only if I set them to zero and save, then the date and save.
Unfortunately, it also converts all non-string falsy fields to Jan 1 1970 at the same time

**Comment by msavin** [comment]
Epic fail. Working on a patch.

**Comment by dpatte** [comment]
It happens to the best of us :)

**Comment by msavin** [comment]
Patch up -> the fix is limited but should work in 'standard' cases.

**Comment by dpatte** [comment]
Thanks. I notice that falsy non-date fields are ok now. Thanks.
But I still can't seem to change a date field that was corrupted with the original error. I will investigate further and if necessary open another issue with exact details.
