### ISSUE TITLE
does not get validated by package aldeed:collection2 why?

### ISSUE THREAD

**Issue by ramstein74** [msavin/Mongol#80]
hello the mongol should not be able so save a record out of the schema specs defined with the package 

aldeed:collection2 

why is that? 
i dont know if this issue should be posted here or in the 

aldeed:collection2

Regards

**Comment by msavin** [comment]
Thanks for submitting the issue. Mongol is compatible with collection2. Did you have an issue with it?

**Comment by JackAdams** [comment]
While Mongol is compatible with collection2 in the sense that they don't cause each other to throw errors, the Mongol code deliberately sidesteps the collection2 validation. This is a design choice to give Mongol maximum control over the database while testing things out from the client side.

I guess a way moving forward would be to have a configuration option that makes Mongol respect the schema.

**Comment by msavin** [comment]
Since it has the same effect as an external DB editor, I think this is a fine behavior. Closing issue.
