### ISSUE TITLE
Collection created in package not visible in Mongol

### ISSUE THREAD

**Issue by wallslide** [msavin/Mongol#83]
We've recently moved some collections of ours into packages. Despite being fully usable within our application, Mongol is seemingly unaware of them. They don't appear in Mongol's list when it is opened with control+M. I've tried placing msavin:mongol at the bottom of our packages file, but still no luck.

**Comment by msavin** [comment]
You'd probably have to move package to load before them in the package file. Otherwise, please read more here:

https://github.com/msavin/Mongol/blob/master/documentation/COMPATIBILITY.md

**Comment by dpatte** [comment]
I also see this issue. I am using vsivsi:file-collection and cannot see it's collection in Mongol. I have tried moving Mongol higher in the package list, but it has no effect in this case. It does use new FileCollection instead of new Mongo.Collection. Is this the issue?
