### ISSUE TITLE
Using autoform with Mongol flashes the previous value when saving a record.

### ISSUE THREAD

**Issue by wesyah234** [msavin/Mongol#84]
This is odd, I recorded it as a screencast... the previous value of the document flashes on the screen when saving a record.  I'm using autoform.

http://screencast-o-matic.com/watch/cofUr4feIz

Oddly, this seems to be intermittent because I'm trying it again and now I can't get it to happen... nothing was changed in the code... so it's probably not a big deal... especially since one wouldn't be using mongol in production, I just wanted to let you know what I saw.

**Comment by JackAdams** [comment]
Very odd. I can't immediately see what might be causing that, but then I'm not too familiar with the autoform internals.

**Comment by msavin** [comment]
Can you confirm if this is for a specific browser or just an overall issue?

**Comment by msavin** [comment]
Closing since there is no reproduction
