### ISSUE TITLE
Mongol is not being activated by Control + M

### ISSUE THREAD

**Issue by allpratik** [msavin/Mongol#85]
Hi,

I just installed mongol and tried to use it in one of the project. But whenever I press "Cntrl+M" it does not show anything on screen.
Though after inspecting the code in console, I saw that Mongol divisions are toggling in the html code but they are not displayed on the screen. 
Can you help me with it?
Thanks in advance!
Regards,
Pratik

**Comment by msavin** [comment]
Can you please list: 
- packages
- css frameworks

I wonder if you have something with a higher z-index overlapping Mongol (though that may not be possible)

**Comment by msavin** [comment]
Also, the result of these would be useful:

Session.get("MeteorToys_display")

and 

Session.set("MeteorToys_display", true)

**Comment by allpratik** [comment]
Following are the Package List for particular meteor project.

autopublish
dburles:google-maps
fuatsengul:leaflet
insecure
iron:router
maazalik:highcharts
meteor-platform
mizzao:bootstrap-3
msavin:mongol
underscore

As you can see I'm using Bootstrap 3 CSS framework.

**Comment by msavin** [comment]
Can you try suggestions from the previous comment

**Comment by 1devNdogs** [comment]
Uncaught Error: {{#each}} currently only accepts arrays, cursors or falsey values.
observe-sequence.js:144  

got this error on ctrl+m or Session.set("MeteorToys_display", true)

**Comment by msavin** [comment]
Hmmm can you provide more details (packages, framework overrides, etc)

**Comment by allpratik** [comment]
@msavin I tried to set Session as you suggested.... the answer for it is "true" always. 
As I mentioned earlier as well, that I can SEE mongol divs being rendered in my codebase when I toggle Cntrl + M. 

But I'm not able to see mongol UI on screen.

So, Mongol is getting ACTIVATED, but something is going wrong while rendering UI. And I had tried this with demo and example projects as well.

**Comment by msavin** [comment]
It's got to be something either sitting over it or overriding its CSS. I'd recommend playing with inspect elemenent. If you can list your libraries, maybe I can help you find it.

**Comment by jorisroling** [comment]
Same here, Ctrl+M not working in Chrome (Mac), but it does work in Safari (Mac).

**Comment by msavin** [comment]
Hmm - do you have any Chrome extensions running?

**Comment by jorisroling** [comment]
Hi Max,

I disabled all the Chrome extensions, and now it works. I (one by one) enabled them again, to check which one was the bad one, but now it works with all of them enabled again. Sorry to have bothered you with such foolishness. Thanks for Mongol!

Regards,

Joris

**Comment by rvzzz** [comment]
Hi, I came across this issue too and I found the problem was about something I was doing wrong about the iron router templates - http://stackoverflow.com/questions/26121109/uncaught-error-no-iron-layout-found-so-you-cant-use-yield.
It now works like a charm to me.. 
Hope it helps someone else. 
@msavin Thank you for this awesome meteor package!
