### ISSUE TITLE
Errors on duplicate (Any Document/Collection). Kills Mongol.

### ISSUE THREAD

**Issue by keesee** [msavin/Mongol#87]
Reproduced on a fresh install of Meteor.  Steps below.

When you attempt to duplication a document in a collection, a duplicate is create and inserted but then it errors out and you have to reload to do anything with it.   Assuming you currently have 3 items in the collection the X/Y counter goes from 3/3 to NaN/4 when duplication. 

Javascript error below.

Uncaught TypeError: Cannot read property '_id' of undefineddocControls.js:81 Template.Mongol_docControls.events.click .Mongol_m_deletetemplate.js:463 (anonymous function)template.js:437 Template._withTemplateInstanceFunctemplate.js:462 (anonymous function)view.js:869 (anonymous function)view.js:523 Blaze._withCurrentViewview.js:868 (anonymous function)events.js:47 (anonymous function)jquery.js:4665 jQuery.event.dispatchjquery.js:4333 jQuery.event.add.elemData.handle

Only happens with Duplicating.  Appears that insert and delete functions work. 

Steps to reproduce:

> run meteor create
> meteor add msavin:mongol
> cd to project
> ## meteor
> 
> define a collection
> ## Test = new Mongo.Collection('test';)
> ## hit Ctrl+M
> 
> add a doc to the test collection
> {
> "test" : "test",
> }

Attempt to duplication the document you just inserted.

**Comment by msavin** [comment]
Poor Mongol. Thanks for letting me know.. looking into it.

**Comment by msavin** [comment]
Fixed, thanks for reporting it! It's very odd that is stopped working.
