### ISSUE TITLE
Is there a limit to the number of collections displayed in mongol?

### ISSUE THREAD

**Issue by wesyah234** [msavin/Mongol#88]
I added a new collection to my app, but I don't see it in the graphical window... currently, it is displaying 6 collections in the window.. could that be the limit?  I can see the contents of the collection using the console, and it's present in my app, just not visible in mongol..??
EDIT: I have confirmed the limit to be 6, as I commented out a different collection in my code and this new one I was looking for started showing up... Is there any way to adjust this limit?

**Comment by msavin** [comment]
There isn't any limit actually.. I've seen guys have over 20 collections. I'm taking a look into it now.

**Comment by msavin** [comment]
I just tested it and looks like it works fine. Can you post the results of the following command on the client: 

Session.get("Mongol").collections

**Comment by wesyah234** [comment]
so sorry!! when I uncommented the code to put the 7th collection back in, it started showing up in mongol... so there must have been something else odd going on at the same time! Sorry to bother you!
