### ISSUE TITLE
Auto-detect collections, so it's just plug-and-play with no configuration

### ISSUE THREAD

**Issue by JackAdams** [msavin/Mongol#9]
No need for the config setup step - just make it plug-and-play, using a default config.  Devs can put in their own custom config if they want to. 

Use the (very lightweight) ([dburles:mongo-collection-instances](https://github.com/dburles/mongo-collection-instances) package.

By default you get all the collections (including namespaced ones) in Mongol.  If someone only wants a subset of the collections, they can `Session.set("Mongol",  {collections: [ ... ], ... })` as usual.

Happy to put a PR together once there's a repo I can fork.

**Comment by msavin** [comment]
Jack,

That's a great idea. With MongoInspector, we had some issues with this approach when the package wasn't listed at the top of the packages list. If you think this approach will have the same issues, maybe we should preserve the option for manual input.

I just pushed up the package source code, looking forward to seeing your PR!
- Max

**Comment by JackAdams** [comment]
Yeah, man.  Putting that PR together is the first thing I'll be doing when I get home from work tonight.  I'm really excited about Mongol and looking forward to using it in all my projects.  "Insanely useful" is an understatement.

**Comment by msavin** [comment]
Awesome man! I can't wait to see it. Let me know if you need any help along the way.

**Comment by msavin** [comment]
On a side note; we did not use the same exact code as @dburles so maybe it won't have the same issue

**Comment by SantoshSrinivas79** [comment]
Just wondering ... is the auto detection incorporated? or was this just closed out.

**Comment by msavin** [comment]
Implemented in 0.4.0 - just run meteor update

**Comment by SantoshSrinivas79** [comment]
What is the configuration i need to do? I currently have the below code in a client `.js` file

``` js
Meteor.startup(function() {

  Session.set("Mongol", {
    'display': true,
    'opacity_normal': ".7",
    'opacity_expand': ".9"
  });

});
```

**Comment by msavin** [comment]
Just remove it 😄
