### ISSUE TITLE
new check error with latests versions of mongol

### ISSUE THREAD

**Issue by tcastelli** [msavin/Mongol#91]
hi, i've got this error all the time when using mongol in a project with audit-argument-checks package, could you add (at least) a check(arguments,[Match.Any]) on that call?

Exception from sub MeteorToys id 6XsCtMeJTTa9WsJMH Er
ror: Did not check() all arguments during publisher 'MeteorToys'
I20150605-15:47:44.087(2)?     at [object Object]._.extend.throwUnlessAllArgumen
tsHaveBeenChecked (packages/check/match.js:357:1)
I20150605-15:47:44.087(2)?     at Object.Match._failIfArgumentsAreNotAllChecked
(packages/check/match.js:112:1)
I20150605-15:47:44.087(2)?     at maybeAuditArgumentChecks (packages/ddp/livedat
a_server.js:1614:1)
I20150605-15:47:44.088(2)?     at [object Object]._.extend._runHandler (packages
/ddp/livedata_server.js:950:1)
I20150605-15:47:44.088(2)?     at [object Object]._.extend._startSubscription (p
ackages/ddp/livedata_server.js:769:1)
I20150605-15:47:44.088(2)?     at [object Object]._.extend.protocol_handlers.sub
 (packages/ddp/livedata_server.js:582:1)
I20150605-15:47:44.089(2)?     at packages/ddp/livedata_server.js:546:1

**Comment by klaseskilson** [comment]
+1, have this issue using Meteor 1.1.0.2 and Mongol 1.0.97.

**Comment by msavin** [comment]
This was fixed in an earlier update. If you are still having the issue, please let me know.
