### ISSUE TITLE
hide Velocity test-related collections

### ISSUE THREAD

**Issue by laurentpayot** [msavin/Mongol#92]
Hi. It would be nice to have an option (checked by default) to hide Velocity test-related collections. At least 8 velocity-prefixed collections are displayed in Mongol along with my "normal" collections. It's a bit messy...

**Comment by kamek-pf** [comment]
+1, would love some sort of filtering options.

**Comment by alesch** [comment]
+1

**Comment by msavin** [comment]
You can use 

```
Package["msavin:mongol"].Mongol.hideCollection("mongoName");
```

to hide collections. I think it would be better to leave it up to you than bundle on support for a ton of packages.

**Comment by kamek-pf** [comment]
Awesome, thanks !

**Comment by kamek-pf** [comment]
I found a bug, here is what I have somewhere in my client code :

```
var ignoredCollections = [
    'velocityTestFiles',
    'velocityFixtureFiles',
    'velocityAggregateReports',
    'velocityLogs',
    'velocityMirrors',
    'velocityOptions',
    'velocityTestReports',
    'kdInfo',
    'meteor_accounts_loginServiceConfiguration'
];

for (var i = 0; i < ignoredCollections.length; i++) {
    Package['msavin:mongol']
        .Mongol
        .hideCollection(ignoredCollections[i]);
}
```

It works fine until you hit F5, or change the URL manually. When one of these two things happens, Mongol fails to find collections ("No collections").

**Comment by laurentpayot** [comment]
@msavin Thanks, it's quite useful! :+1: 

@kamek-pf just add <code>Package["msavin:mongol"].Mongol.detectCollections()</code> before your loop to fix your bug (that I experienced too). Mongol is a debugOnly package so to avoid an error message in production I added a condition to check if Mongol is defined. In Coffeescript:

<pre>
if Package["msavin:mongol"]
    mongolIgnoredCollections = [
        'velocityTestFiles'
        'velocityFixtureFiles'
        'velocityAggregateReports'
        'velocityLogs'
        'velocityMirrors'
        'velocityOptions'
        'velocityTestReports'
    ]
    Package["msavin:mongol"].Mongol.detectCollections()
    Package["msavin:mongol"].Mongol.hideCollection(c) for c in mongolIgnoredCollections
</pre>

**Comment by kamek-pf** [comment]
@laurentpayot thanks for the `detectCollections()` tip ;D
@msavin I guess you could close the ticket, it would help if this was documented somewhere though. Thanks for this nice tool btw :D

**Comment by laurentpayot** [comment]
If everything is fine then I'm closing the ticket...
