### ISSUE TITLE
update mongol when navigating pages

### ISSUE THREAD

**Issue by avalanche1** [msavin/Mongol#93]
It'd be nice if Mongol updated itself with new values when I navigate to a new page.
Currently I have to press `ctrl+m` two times to re-open it and see new values.

**Comment by msavin** [comment]
Can you please elaborate? When you switch routes the contents update automatically.

**Comment by avalanche1** [comment]
Ah, yes. Mongol does it. Jetsetter doesn't.
When you switch routes the Jetsetter contents do not update automatically.

**Comment by msavin** [comment]
They should every 3 seconds. If you spot an issue, please create a report for JetSetter
