### ISSUE TITLE
Collections Not Being Read from 'Mongol' Session

### ISSUE THREAD

**Issue by eliasthompson** [msavin/Mongol#94]
Ever since the last version update I did of Mongol, it hasn't been reading the collections array and now just shows every collection. At first I thought it was something I messed up on my project, but now I am seeing it on multiple projects after updating on different machines. Any way to put this functionality back in, or is this something being moved over to the Pro version?

**Comment by msavin** [comment]
Nothing was removed from the free version, thought you may like the bonus features of the paid version. Mongol stopped using Session in favor of its own reactive dictionary. See the new approach here:

https://github.com/msavin/Mongol/blob/master/documentation/COMPATIBILITY.md

**Comment by eliasthompson** [comment]
Thanks for the heads up!

**Comment by eliasthompson** [comment]
Is this still the way to do this? I haven't seen anything in the compatibility file change, and I've been getting a "Cannot read property 'set' of undefined" error lately.

![image](https://cloud.githubusercontent.com/assets/3383889/8812215/a5a865ae-2faf-11e5-94f7-7dd991d9a75c.png)

**Comment by eliasthompson** [comment]
Never mind, I'm an idiot and didn't update to the latest version.
