### ISSUE TITLE
Include transformations in documents

### ISSUE THREAD

**Issue by petermikitsh** [msavin/Mongol#95]
Properties added during transformations are not shown in the Mongol window.

**Comment by JackAdams** [comment]
This is deliberate. Mongol gives a reflection of what is in the mongo (or rather, minimongo) database. Consider what would happen if a `transform` added a function property - how would that be reflected (or edited!) via the Mongol UI?

**Comment by petermikitsh** [comment]
Considering that in the context of the application, all documents go through transformation by default, it would be a meaning default to show added properties. Perhaps out the door, properties that are functions are simply represented as such as not editable through the mongol console.

**Comment by JackAdams** [comment]
Yeah, I hear what you're saying.  At the moment, showing the results of transforms (including possible function-type properties) is non-trivial.  It would entail a pretty large scale re-write of the Mongol internals.

**Comment by petermikitsh** [comment]
Ah well that's a shame. Perhaps you and @msavin could consider the feature for a future major release!
