### ISSUE TITLE
Failed to decode font LiberationMono-Bold

### ISSUE THREAD

**Issue by ghost** [msavin/Mongol#98]
Getting the following warning:

Failed to decode downloaded font: http://localhost:3000/packages/meteortoys_toykit/public/LiberationMono-Bold.ttf

msavin:mongol version 1.1.0

**Comment by ghost** [comment]
meteortoys:toykit 0.8.2

**Comment by saturnaut** [comment]
Getting the error as well with only non-pro Mongol installed.

**Comment by msavin** [comment]
Fixed with Mongol 1.1.1, for more info: 

https://github.com/msavin/Mongol/issues/99#issuecomment-128485689
